# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

abbr --add k "kubectl"
abbr --add ksys "kubectl --namespace=kube-system"
abbr --add ka "kubectl apply --recursive -f"
abbr --add ksysa "kubectl --namespace=kube-system apply --recursive -f"
abbr --add kak "kubectl apply -k"
abbr --add kk "kubectl kustomize"
abbr --add kex "kubectl exec -i -t"
abbr --add ksysex "kubectl --namespace=kube-system exec -i -t"
abbr --add klo "kubectl logs -f"
abbr --add ksyslo "kubectl --namespace=kube-system logs -f"
abbr --add klop "kubectl logs -f -p"
abbr --add ksyslop "kubectl --namespace=kube-system logs -f -p"
abbr --add kp "kubectl proxy"
abbr --add kpf "kubectl port-forward"
abbr --add kg "kubectl get"
abbr --add ksysg "kubectl --namespace=kube-system get"
abbr --add kd "kubectl describe"
abbr --add ksysd "kubectl --namespace=kube-system describe"
abbr --add krm "kubectl delete"
abbr --add ksysrm "kubectl --namespace=kube-system delete"
abbr --add krun "kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add ksysrun "kubectl --namespace=kube-system run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t"
abbr --add kgpo "kubectl get pods"
abbr --add ksysgpo "kubectl --namespace=kube-system get pods"
abbr --add kdpo "kubectl describe pods"
abbr --add ksysdpo "kubectl --namespace=kube-system describe pods"
abbr --add krmpo "kubectl delete pods"
abbr --add ksysrmpo "kubectl --namespace=kube-system delete pods"
abbr --add kgdep "kubectl get deployment"
abbr --add ksysgdep "kubectl --namespace=kube-system get deployment"
abbr --add kddep "kubectl describe deployment"
abbr --add ksysddep "kubectl --namespace=kube-system describe deployment"
abbr --add krmdep "kubectl delete deployment"
abbr --add ksysrmdep "kubectl --namespace=kube-system delete deployment"
abbr --add kgsts "kubectl get statefulset"
abbr --add ksysgsts "kubectl --namespace=kube-system get statefulset"
abbr --add kdsts "kubectl describe statefulset"
abbr --add ksysdsts "kubectl --namespace=kube-system describe statefulset"
abbr --add krmsts "kubectl delete statefulset"
abbr --add ksysrmsts "kubectl --namespace=kube-system delete statefulset"
abbr --add kgsvc "kubectl get service"
abbr --add ksysgsvc "kubectl --namespace=kube-system get service"
abbr --add kdsvc "kubectl describe service"
abbr --add ksysdsvc "kubectl --namespace=kube-system describe service"
abbr --add krmsvc "kubectl delete service"
abbr --add ksysrmsvc "kubectl --namespace=kube-system delete service"
abbr --add kging "kubectl get ingress"
abbr --add ksysging "kubectl --namespace=kube-system get ingress"
abbr --add kding "kubectl describe ingress"
abbr --add ksysding "kubectl --namespace=kube-system describe ingress"
abbr --add krming "kubectl delete ingress"
abbr --add ksysrming "kubectl --namespace=kube-system delete ingress"
abbr --add kgcm "kubectl get configmap"
abbr --add ksysgcm "kubectl --namespace=kube-system get configmap"
abbr --add kdcm "kubectl describe configmap"
abbr --add ksysdcm "kubectl --namespace=kube-system describe configmap"
abbr --add krmcm "kubectl delete configmap"
abbr --add ksysrmcm "kubectl --namespace=kube-system delete configmap"
abbr --add kgsec "kubectl get secret"
abbr --add ksysgsec "kubectl --namespace=kube-system get secret"
abbr --add kdsec "kubectl describe secret"
abbr --add ksysdsec "kubectl --namespace=kube-system describe secret"
abbr --add krmsec "kubectl delete secret"
abbr --add ksysrmsec "kubectl --namespace=kube-system delete secret"
abbr --add kgno "kubectl get nodes"
abbr --add kdno "kubectl describe nodes"
abbr --add kgns "kubectl get namespaces"
abbr --add kdns "kubectl describe namespaces"
abbr --add krmns "kubectl delete namespaces"
abbr --add kgoyaml "kubectl get -o=yaml"
abbr --add ksysgoyaml "kubectl --namespace=kube-system get -o=yaml"
abbr --add kgpooyaml "kubectl get pods -o=yaml"
abbr --add ksysgpooyaml "kubectl --namespace=kube-system get pods -o=yaml"
abbr --add kgdepoyaml "kubectl get deployment -o=yaml"
abbr --add ksysgdepoyaml "kubectl --namespace=kube-system get deployment -o=yaml"
abbr --add kgstsoyaml "kubectl get statefulset -o=yaml"
abbr --add ksysgstsoyaml "kubectl --namespace=kube-system get statefulset -o=yaml"
abbr --add kgsvcoyaml "kubectl get service -o=yaml"
abbr --add ksysgsvcoyaml "kubectl --namespace=kube-system get service -o=yaml"
abbr --add kgingoyaml "kubectl get ingress -o=yaml"
abbr --add ksysgingoyaml "kubectl --namespace=kube-system get ingress -o=yaml"
abbr --add kgcmoyaml "kubectl get configmap -o=yaml"
abbr --add ksysgcmoyaml "kubectl --namespace=kube-system get configmap -o=yaml"
abbr --add kgsecoyaml "kubectl get secret -o=yaml"
abbr --add ksysgsecoyaml "kubectl --namespace=kube-system get secret -o=yaml"
abbr --add kgnooyaml "kubectl get nodes -o=yaml"
abbr --add kgnsoyaml "kubectl get namespaces -o=yaml"
abbr --add kgowide "kubectl get -o=wide"
abbr --add ksysgowide "kubectl --namespace=kube-system get -o=wide"
abbr --add kgpoowide "kubectl get pods -o=wide"
abbr --add ksysgpoowide "kubectl --namespace=kube-system get pods -o=wide"
abbr --add kgdepowide "kubectl get deployment -o=wide"
abbr --add ksysgdepowide "kubectl --namespace=kube-system get deployment -o=wide"
abbr --add kgstsowide "kubectl get statefulset -o=wide"
abbr --add ksysgstsowide "kubectl --namespace=kube-system get statefulset -o=wide"
abbr --add kgsvcowide "kubectl get service -o=wide"
abbr --add ksysgsvcowide "kubectl --namespace=kube-system get service -o=wide"
abbr --add kgingowide "kubectl get ingress -o=wide"
abbr --add ksysgingowide "kubectl --namespace=kube-system get ingress -o=wide"
abbr --add kgcmowide "kubectl get configmap -o=wide"
abbr --add ksysgcmowide "kubectl --namespace=kube-system get configmap -o=wide"
abbr --add kgsecowide "kubectl get secret -o=wide"
abbr --add ksysgsecowide "kubectl --namespace=kube-system get secret -o=wide"
abbr --add kgnoowide "kubectl get nodes -o=wide"
abbr --add kgnsowide "kubectl get namespaces -o=wide"
abbr --add kgojson "kubectl get -o=json"
abbr --add ksysgojson "kubectl --namespace=kube-system get -o=json"
abbr --add kgpoojson "kubectl get pods -o=json"
abbr --add ksysgpoojson "kubectl --namespace=kube-system get pods -o=json"
abbr --add kgdepojson "kubectl get deployment -o=json"
abbr --add ksysgdepojson "kubectl --namespace=kube-system get deployment -o=json"
abbr --add kgstsojson "kubectl get statefulset -o=json"
abbr --add ksysgstsojson "kubectl --namespace=kube-system get statefulset -o=json"
abbr --add kgsvcojson "kubectl get service -o=json"
abbr --add ksysgsvcojson "kubectl --namespace=kube-system get service -o=json"
abbr --add kgingojson "kubectl get ingress -o=json"
abbr --add ksysgingojson "kubectl --namespace=kube-system get ingress -o=json"
abbr --add kgcmojson "kubectl get configmap -o=json"
abbr --add ksysgcmojson "kubectl --namespace=kube-system get configmap -o=json"
abbr --add kgsecojson "kubectl get secret -o=json"
abbr --add ksysgsecojson "kubectl --namespace=kube-system get secret -o=json"
abbr --add kgnoojson "kubectl get nodes -o=json"
abbr --add kgnsojson "kubectl get namespaces -o=json"
abbr --add kgall "kubectl get --all-namespaces"
abbr --add kdall "kubectl describe --all-namespaces"
abbr --add kgpoall "kubectl get pods --all-namespaces"
abbr --add kdpoall "kubectl describe pods --all-namespaces"
abbr --add kgdepall "kubectl get deployment --all-namespaces"
abbr --add kddepall "kubectl describe deployment --all-namespaces"
abbr --add kgstsall "kubectl get statefulset --all-namespaces"
abbr --add kdstsall "kubectl describe statefulset --all-namespaces"
abbr --add kgsvcall "kubectl get service --all-namespaces"
abbr --add kdsvcall "kubectl describe service --all-namespaces"
abbr --add kgingall "kubectl get ingress --all-namespaces"
abbr --add kdingall "kubectl describe ingress --all-namespaces"
abbr --add kgcmall "kubectl get configmap --all-namespaces"
abbr --add kdcmall "kubectl describe configmap --all-namespaces"
abbr --add kgsecall "kubectl get secret --all-namespaces"
abbr --add kdsecall "kubectl describe secret --all-namespaces"
abbr --add kgnsall "kubectl get namespaces --all-namespaces"
abbr --add kdnsall "kubectl describe namespaces --all-namespaces"
abbr --add kgsl "kubectl get --show-labels"
abbr --add ksysgsl "kubectl --namespace=kube-system get --show-labels"
abbr --add kgposl "kubectl get pods --show-labels"
abbr --add ksysgposl "kubectl --namespace=kube-system get pods --show-labels"
abbr --add kgdepsl "kubectl get deployment --show-labels"
abbr --add ksysgdepsl "kubectl --namespace=kube-system get deployment --show-labels"
abbr --add kgstssl "kubectl get statefulset --show-labels"
abbr --add ksysgstssl "kubectl --namespace=kube-system get statefulset --show-labels"
abbr --add kgsvcsl "kubectl get service --show-labels"
abbr --add ksysgsvcsl "kubectl --namespace=kube-system get service --show-labels"
abbr --add kgingsl "kubectl get ingress --show-labels"
abbr --add ksysgingsl "kubectl --namespace=kube-system get ingress --show-labels"
abbr --add kgcmsl "kubectl get configmap --show-labels"
abbr --add ksysgcmsl "kubectl --namespace=kube-system get configmap --show-labels"
abbr --add kgsecsl "kubectl get secret --show-labels"
abbr --add ksysgsecsl "kubectl --namespace=kube-system get secret --show-labels"
abbr --add kgnosl "kubectl get nodes --show-labels"
abbr --add kgnssl "kubectl get namespaces --show-labels"
abbr --add krmall "kubectl delete --all"
abbr --add ksysrmall "kubectl --namespace=kube-system delete --all"
abbr --add krmpoall "kubectl delete pods --all"
abbr --add ksysrmpoall "kubectl --namespace=kube-system delete pods --all"
abbr --add krmdepall "kubectl delete deployment --all"
abbr --add ksysrmdepall "kubectl --namespace=kube-system delete deployment --all"
abbr --add krmstsall "kubectl delete statefulset --all"
abbr --add ksysrmstsall "kubectl --namespace=kube-system delete statefulset --all"
abbr --add krmsvcall "kubectl delete service --all"
abbr --add ksysrmsvcall "kubectl --namespace=kube-system delete service --all"
abbr --add krmingall "kubectl delete ingress --all"
abbr --add ksysrmingall "kubectl --namespace=kube-system delete ingress --all"
abbr --add krmcmall "kubectl delete configmap --all"
abbr --add ksysrmcmall "kubectl --namespace=kube-system delete configmap --all"
abbr --add krmsecall "kubectl delete secret --all"
abbr --add ksysrmsecall "kubectl --namespace=kube-system delete secret --all"
abbr --add krmnsall "kubectl delete namespaces --all"
abbr --add kgw "kubectl get --watch"
abbr --add ksysgw "kubectl --namespace=kube-system get --watch"
abbr --add kgpow "kubectl get pods --watch"
abbr --add ksysgpow "kubectl --namespace=kube-system get pods --watch"
abbr --add kgdepw "kubectl get deployment --watch"
abbr --add ksysgdepw "kubectl --namespace=kube-system get deployment --watch"
abbr --add kgstsw "kubectl get statefulset --watch"
abbr --add ksysgstsw "kubectl --namespace=kube-system get statefulset --watch"
abbr --add kgsvcw "kubectl get service --watch"
abbr --add ksysgsvcw "kubectl --namespace=kube-system get service --watch"
abbr --add kgingw "kubectl get ingress --watch"
abbr --add ksysgingw "kubectl --namespace=kube-system get ingress --watch"
abbr --add kgcmw "kubectl get configmap --watch"
abbr --add ksysgcmw "kubectl --namespace=kube-system get configmap --watch"
abbr --add kgsecw "kubectl get secret --watch"
abbr --add ksysgsecw "kubectl --namespace=kube-system get secret --watch"
abbr --add kgnow "kubectl get nodes --watch"
abbr --add kgnsw "kubectl get namespaces --watch"
abbr --add kgoyamlall "kubectl get -o=yaml --all-namespaces"
abbr --add kgpooyamlall "kubectl get pods -o=yaml --all-namespaces"
abbr --add kgdepoyamlall "kubectl get deployment -o=yaml --all-namespaces"
abbr --add kgstsoyamlall "kubectl get statefulset -o=yaml --all-namespaces"
abbr --add kgsvcoyamlall "kubectl get service -o=yaml --all-namespaces"
abbr --add kgingoyamlall "kubectl get ingress -o=yaml --all-namespaces"
abbr --add kgcmoyamlall "kubectl get configmap -o=yaml --all-namespaces"
abbr --add kgsecoyamlall "kubectl get secret -o=yaml --all-namespaces"
abbr --add kgnsoyamlall "kubectl get namespaces -o=yaml --all-namespaces"
abbr --add kgalloyaml "kubectl get --all-namespaces -o=yaml"
abbr --add kgpoalloyaml "kubectl get pods --all-namespaces -o=yaml"
abbr --add kgdepalloyaml "kubectl get deployment --all-namespaces -o=yaml"
abbr --add kgstsalloyaml "kubectl get statefulset --all-namespaces -o=yaml"
abbr --add kgsvcalloyaml "kubectl get service --all-namespaces -o=yaml"
abbr --add kgingalloyaml "kubectl get ingress --all-namespaces -o=yaml"
abbr --add kgcmalloyaml "kubectl get configmap --all-namespaces -o=yaml"
abbr --add kgsecalloyaml "kubectl get secret --all-namespaces -o=yaml"
abbr --add kgnsalloyaml "kubectl get namespaces --all-namespaces -o=yaml"
abbr --add kgwoyaml "kubectl get --watch -o=yaml"
abbr --add ksysgwoyaml "kubectl --namespace=kube-system get --watch -o=yaml"
abbr --add kgpowoyaml "kubectl get pods --watch -o=yaml"
abbr --add ksysgpowoyaml "kubectl --namespace=kube-system get pods --watch -o=yaml"
abbr --add kgdepwoyaml "kubectl get deployment --watch -o=yaml"
abbr --add ksysgdepwoyaml "kubectl --namespace=kube-system get deployment --watch -o=yaml"
abbr --add kgstswoyaml "kubectl get statefulset --watch -o=yaml"
abbr --add ksysgstswoyaml "kubectl --namespace=kube-system get statefulset --watch -o=yaml"
abbr --add kgsvcwoyaml "kubectl get service --watch -o=yaml"
abbr --add ksysgsvcwoyaml "kubectl --namespace=kube-system get service --watch -o=yaml"
abbr --add kgingwoyaml "kubectl get ingress --watch -o=yaml"
abbr --add ksysgingwoyaml "kubectl --namespace=kube-system get ingress --watch -o=yaml"
abbr --add kgcmwoyaml "kubectl get configmap --watch -o=yaml"
abbr --add ksysgcmwoyaml "kubectl --namespace=kube-system get configmap --watch -o=yaml"
abbr --add kgsecwoyaml "kubectl get secret --watch -o=yaml"
abbr --add ksysgsecwoyaml "kubectl --namespace=kube-system get secret --watch -o=yaml"
abbr --add kgnowoyaml "kubectl get nodes --watch -o=yaml"
abbr --add kgnswoyaml "kubectl get namespaces --watch -o=yaml"
abbr --add kgowideall "kubectl get -o=wide --all-namespaces"
abbr --add kgpoowideall "kubectl get pods -o=wide --all-namespaces"
abbr --add kgdepowideall "kubectl get deployment -o=wide --all-namespaces"
abbr --add kgstsowideall "kubectl get statefulset -o=wide --all-namespaces"
abbr --add kgsvcowideall "kubectl get service -o=wide --all-namespaces"
abbr --add kgingowideall "kubectl get ingress -o=wide --all-namespaces"
abbr --add kgcmowideall "kubectl get configmap -o=wide --all-namespaces"
abbr --add kgsecowideall "kubectl get secret -o=wide --all-namespaces"
abbr --add kgnsowideall "kubectl get namespaces -o=wide --all-namespaces"
abbr --add kgallowide "kubectl get --all-namespaces -o=wide"
abbr --add kgpoallowide "kubectl get pods --all-namespaces -o=wide"
abbr --add kgdepallowide "kubectl get deployment --all-namespaces -o=wide"
abbr --add kgstsallowide "kubectl get statefulset --all-namespaces -o=wide"
abbr --add kgsvcallowide "kubectl get service --all-namespaces -o=wide"
abbr --add kgingallowide "kubectl get ingress --all-namespaces -o=wide"
abbr --add kgcmallowide "kubectl get configmap --all-namespaces -o=wide"
abbr --add kgsecallowide "kubectl get secret --all-namespaces -o=wide"
abbr --add kgnsallowide "kubectl get namespaces --all-namespaces -o=wide"
abbr --add kgowidesl "kubectl get -o=wide --show-labels"
abbr --add ksysgowidesl "kubectl --namespace=kube-system get -o=wide --show-labels"
abbr --add kgpoowidesl "kubectl get pods -o=wide --show-labels"
abbr --add ksysgpoowidesl "kubectl --namespace=kube-system get pods -o=wide --show-labels"
abbr --add kgdepowidesl "kubectl get deployment -o=wide --show-labels"
abbr --add ksysgdepowidesl "kubectl --namespace=kube-system get deployment -o=wide --show-labels"
abbr --add kgstsowidesl "kubectl get statefulset -o=wide --show-labels"
abbr --add ksysgstsowidesl "kubectl --namespace=kube-system get statefulset -o=wide --show-labels"
abbr --add kgsvcowidesl "kubectl get service -o=wide --show-labels"
abbr --add ksysgsvcowidesl "kubectl --namespace=kube-system get service -o=wide --show-labels"
abbr --add kgingowidesl "kubectl get ingress -o=wide --show-labels"
abbr --add ksysgingowidesl "kubectl --namespace=kube-system get ingress -o=wide --show-labels"
abbr --add kgcmowidesl "kubectl get configmap -o=wide --show-labels"
abbr --add ksysgcmowidesl "kubectl --namespace=kube-system get configmap -o=wide --show-labels"
abbr --add kgsecowidesl "kubectl get secret -o=wide --show-labels"
abbr --add ksysgsecowidesl "kubectl --namespace=kube-system get secret -o=wide --show-labels"
abbr --add kgnoowidesl "kubectl get nodes -o=wide --show-labels"
abbr --add kgnsowidesl "kubectl get namespaces -o=wide --show-labels"
abbr --add kgslowide "kubectl get --show-labels -o=wide"
abbr --add ksysgslowide "kubectl --namespace=kube-system get --show-labels -o=wide"
abbr --add kgposlowide "kubectl get pods --show-labels -o=wide"
abbr --add ksysgposlowide "kubectl --namespace=kube-system get pods --show-labels -o=wide"
abbr --add kgdepslowide "kubectl get deployment --show-labels -o=wide"
abbr --add ksysgdepslowide "kubectl --namespace=kube-system get deployment --show-labels -o=wide"
abbr --add kgstsslowide "kubectl get statefulset --show-labels -o=wide"
abbr --add ksysgstsslowide "kubectl --namespace=kube-system get statefulset --show-labels -o=wide"
abbr --add kgsvcslowide "kubectl get service --show-labels -o=wide"
abbr --add ksysgsvcslowide "kubectl --namespace=kube-system get service --show-labels -o=wide"
abbr --add kgingslowide "kubectl get ingress --show-labels -o=wide"
abbr --add ksysgingslowide "kubectl --namespace=kube-system get ingress --show-labels -o=wide"
abbr --add kgcmslowide "kubectl get configmap --show-labels -o=wide"
abbr --add ksysgcmslowide "kubectl --namespace=kube-system get configmap --show-labels -o=wide"
abbr --add kgsecslowide "kubectl get secret --show-labels -o=wide"
abbr --add ksysgsecslowide "kubectl --namespace=kube-system get secret --show-labels -o=wide"
abbr --add kgnoslowide "kubectl get nodes --show-labels -o=wide"
abbr --add kgnsslowide "kubectl get namespaces --show-labels -o=wide"
abbr --add kgwowide "kubectl get --watch -o=wide"
abbr --add ksysgwowide "kubectl --namespace=kube-system get --watch -o=wide"
abbr --add kgpowowide "kubectl get pods --watch -o=wide"
abbr --add ksysgpowowide "kubectl --namespace=kube-system get pods --watch -o=wide"
abbr --add kgdepwowide "kubectl get deployment --watch -o=wide"
abbr --add ksysgdepwowide "kubectl --namespace=kube-system get deployment --watch -o=wide"
abbr --add kgstswowide "kubectl get statefulset --watch -o=wide"
abbr --add ksysgstswowide "kubectl --namespace=kube-system get statefulset --watch -o=wide"
abbr --add kgsvcwowide "kubectl get service --watch -o=wide"
abbr --add ksysgsvcwowide "kubectl --namespace=kube-system get service --watch -o=wide"
abbr --add kgingwowide "kubectl get ingress --watch -o=wide"
abbr --add ksysgingwowide "kubectl --namespace=kube-system get ingress --watch -o=wide"
abbr --add kgcmwowide "kubectl get configmap --watch -o=wide"
abbr --add ksysgcmwowide "kubectl --namespace=kube-system get configmap --watch -o=wide"
abbr --add kgsecwowide "kubectl get secret --watch -o=wide"
abbr --add ksysgsecwowide "kubectl --namespace=kube-system get secret --watch -o=wide"
abbr --add kgnowowide "kubectl get nodes --watch -o=wide"
abbr --add kgnswowide "kubectl get namespaces --watch -o=wide"
abbr --add kgojsonall "kubectl get -o=json --all-namespaces"
abbr --add kgpoojsonall "kubectl get pods -o=json --all-namespaces"
abbr --add kgdepojsonall "kubectl get deployment -o=json --all-namespaces"
abbr --add kgstsojsonall "kubectl get statefulset -o=json --all-namespaces"
abbr --add kgsvcojsonall "kubectl get service -o=json --all-namespaces"
abbr --add kgingojsonall "kubectl get ingress -o=json --all-namespaces"
abbr --add kgcmojsonall "kubectl get configmap -o=json --all-namespaces"
abbr --add kgsecojsonall "kubectl get secret -o=json --all-namespaces"
abbr --add kgnsojsonall "kubectl get namespaces -o=json --all-namespaces"
abbr --add kgallojson "kubectl get --all-namespaces -o=json"
abbr --add kgpoallojson "kubectl get pods --all-namespaces -o=json"
abbr --add kgdepallojson "kubectl get deployment --all-namespaces -o=json"
abbr --add kgstsallojson "kubectl get statefulset --all-namespaces -o=json"
abbr --add kgsvcallojson "kubectl get service --all-namespaces -o=json"
abbr --add kgingallojson "kubectl get ingress --all-namespaces -o=json"
abbr --add kgcmallojson "kubectl get configmap --all-namespaces -o=json"
abbr --add kgsecallojson "kubectl get secret --all-namespaces -o=json"
abbr --add kgnsallojson "kubectl get namespaces --all-namespaces -o=json"
abbr --add kgwojson "kubectl get --watch -o=json"
abbr --add ksysgwojson "kubectl --namespace=kube-system get --watch -o=json"
abbr --add kgpowojson "kubectl get pods --watch -o=json"
abbr --add ksysgpowojson "kubectl --namespace=kube-system get pods --watch -o=json"
abbr --add kgdepwojson "kubectl get deployment --watch -o=json"
abbr --add ksysgdepwojson "kubectl --namespace=kube-system get deployment --watch -o=json"
abbr --add kgstswojson "kubectl get statefulset --watch -o=json"
abbr --add ksysgstswojson "kubectl --namespace=kube-system get statefulset --watch -o=json"
abbr --add kgsvcwojson "kubectl get service --watch -o=json"
abbr --add ksysgsvcwojson "kubectl --namespace=kube-system get service --watch -o=json"
abbr --add kgingwojson "kubectl get ingress --watch -o=json"
abbr --add ksysgingwojson "kubectl --namespace=kube-system get ingress --watch -o=json"
abbr --add kgcmwojson "kubectl get configmap --watch -o=json"
abbr --add ksysgcmwojson "kubectl --namespace=kube-system get configmap --watch -o=json"
abbr --add kgsecwojson "kubectl get secret --watch -o=json"
abbr --add ksysgsecwojson "kubectl --namespace=kube-system get secret --watch -o=json"
abbr --add kgnowojson "kubectl get nodes --watch -o=json"
abbr --add kgnswojson "kubectl get namespaces --watch -o=json"
abbr --add kgallsl "kubectl get --all-namespaces --show-labels"
abbr --add kgpoallsl "kubectl get pods --all-namespaces --show-labels"
abbr --add kgdepallsl "kubectl get deployment --all-namespaces --show-labels"
abbr --add kgstsallsl "kubectl get statefulset --all-namespaces --show-labels"
abbr --add kgsvcallsl "kubectl get service --all-namespaces --show-labels"
abbr --add kgingallsl "kubectl get ingress --all-namespaces --show-labels"
abbr --add kgcmallsl "kubectl get configmap --all-namespaces --show-labels"
abbr --add kgsecallsl "kubectl get secret --all-namespaces --show-labels"
abbr --add kgnsallsl "kubectl get namespaces --all-namespaces --show-labels"
abbr --add kgslall "kubectl get --show-labels --all-namespaces"
abbr --add kgposlall "kubectl get pods --show-labels --all-namespaces"
abbr --add kgdepslall "kubectl get deployment --show-labels --all-namespaces"
abbr --add kgstsslall "kubectl get statefulset --show-labels --all-namespaces"
abbr --add kgsvcslall "kubectl get service --show-labels --all-namespaces"
abbr --add kgingslall "kubectl get ingress --show-labels --all-namespaces"
abbr --add kgcmslall "kubectl get configmap --show-labels --all-namespaces"
abbr --add kgsecslall "kubectl get secret --show-labels --all-namespaces"
abbr --add kgnsslall "kubectl get namespaces --show-labels --all-namespaces"
abbr --add kgallw "kubectl get --all-namespaces --watch"
abbr --add kgpoallw "kubectl get pods --all-namespaces --watch"
abbr --add kgdepallw "kubectl get deployment --all-namespaces --watch"
abbr --add kgstsallw "kubectl get statefulset --all-namespaces --watch"
abbr --add kgsvcallw "kubectl get service --all-namespaces --watch"
abbr --add kgingallw "kubectl get ingress --all-namespaces --watch"
abbr --add kgcmallw "kubectl get configmap --all-namespaces --watch"
abbr --add kgsecallw "kubectl get secret --all-namespaces --watch"
abbr --add kgnsallw "kubectl get namespaces --all-namespaces --watch"
abbr --add kgwall "kubectl get --watch --all-namespaces"
abbr --add kgpowall "kubectl get pods --watch --all-namespaces"
abbr --add kgdepwall "kubectl get deployment --watch --all-namespaces"
abbr --add kgstswall "kubectl get statefulset --watch --all-namespaces"
abbr --add kgsvcwall "kubectl get service --watch --all-namespaces"
abbr --add kgingwall "kubectl get ingress --watch --all-namespaces"
abbr --add kgcmwall "kubectl get configmap --watch --all-namespaces"
abbr --add kgsecwall "kubectl get secret --watch --all-namespaces"
abbr --add kgnswall "kubectl get namespaces --watch --all-namespaces"
abbr --add kgslw "kubectl get --show-labels --watch"
abbr --add ksysgslw "kubectl --namespace=kube-system get --show-labels --watch"
abbr --add kgposlw "kubectl get pods --show-labels --watch"
abbr --add ksysgposlw "kubectl --namespace=kube-system get pods --show-labels --watch"
abbr --add kgdepslw "kubectl get deployment --show-labels --watch"
abbr --add ksysgdepslw "kubectl --namespace=kube-system get deployment --show-labels --watch"
abbr --add kgstsslw "kubectl get statefulset --show-labels --watch"
abbr --add ksysgstsslw "kubectl --namespace=kube-system get statefulset --show-labels --watch"
abbr --add kgsvcslw "kubectl get service --show-labels --watch"
abbr --add ksysgsvcslw "kubectl --namespace=kube-system get service --show-labels --watch"
abbr --add kgingslw "kubectl get ingress --show-labels --watch"
abbr --add ksysgingslw "kubectl --namespace=kube-system get ingress --show-labels --watch"
abbr --add kgcmslw "kubectl get configmap --show-labels --watch"
abbr --add ksysgcmslw "kubectl --namespace=kube-system get configmap --show-labels --watch"
abbr --add kgsecslw "kubectl get secret --show-labels --watch"
abbr --add ksysgsecslw "kubectl --namespace=kube-system get secret --show-labels --watch"
abbr --add kgnoslw "kubectl get nodes --show-labels --watch"
abbr --add kgnsslw "kubectl get namespaces --show-labels --watch"
abbr --add kgwsl "kubectl get --watch --show-labels"
abbr --add ksysgwsl "kubectl --namespace=kube-system get --watch --show-labels"
abbr --add kgpowsl "kubectl get pods --watch --show-labels"
abbr --add ksysgpowsl "kubectl --namespace=kube-system get pods --watch --show-labels"
abbr --add kgdepwsl "kubectl get deployment --watch --show-labels"
abbr --add ksysgdepwsl "kubectl --namespace=kube-system get deployment --watch --show-labels"
abbr --add kgstswsl "kubectl get statefulset --watch --show-labels"
abbr --add ksysgstswsl "kubectl --namespace=kube-system get statefulset --watch --show-labels"
abbr --add kgsvcwsl "kubectl get service --watch --show-labels"
abbr --add ksysgsvcwsl "kubectl --namespace=kube-system get service --watch --show-labels"
abbr --add kgingwsl "kubectl get ingress --watch --show-labels"
abbr --add ksysgingwsl "kubectl --namespace=kube-system get ingress --watch --show-labels"
abbr --add kgcmwsl "kubectl get configmap --watch --show-labels"
abbr --add ksysgcmwsl "kubectl --namespace=kube-system get configmap --watch --show-labels"
abbr --add kgsecwsl "kubectl get secret --watch --show-labels"
abbr --add ksysgsecwsl "kubectl --namespace=kube-system get secret --watch --show-labels"
abbr --add kgnowsl "kubectl get nodes --watch --show-labels"
abbr --add kgnswsl "kubectl get namespaces --watch --show-labels"
abbr --add kgallwoyaml "kubectl get --all-namespaces --watch -o=yaml"
abbr --add kgpoallwoyaml "kubectl get pods --all-namespaces --watch -o=yaml"
abbr --add kgdepallwoyaml "kubectl get deployment --all-namespaces --watch -o=yaml"
abbr --add kgstsallwoyaml "kubectl get statefulset --all-namespaces --watch -o=yaml"
abbr --add kgsvcallwoyaml "kubectl get service --all-namespaces --watch -o=yaml"
abbr --add kgingallwoyaml "kubectl get ingress --all-namespaces --watch -o=yaml"
abbr --add kgcmallwoyaml "kubectl get configmap --all-namespaces --watch -o=yaml"
abbr --add kgsecallwoyaml "kubectl get secret --all-namespaces --watch -o=yaml"
abbr --add kgnsallwoyaml "kubectl get namespaces --all-namespaces --watch -o=yaml"
abbr --add kgwoyamlall "kubectl get --watch -o=yaml --all-namespaces"
abbr --add kgpowoyamlall "kubectl get pods --watch -o=yaml --all-namespaces"
abbr --add kgdepwoyamlall "kubectl get deployment --watch -o=yaml --all-namespaces"
abbr --add kgstswoyamlall "kubectl get statefulset --watch -o=yaml --all-namespaces"
abbr --add kgsvcwoyamlall "kubectl get service --watch -o=yaml --all-namespaces"
abbr --add kgingwoyamlall "kubectl get ingress --watch -o=yaml --all-namespaces"
abbr --add kgcmwoyamlall "kubectl get configmap --watch -o=yaml --all-namespaces"
abbr --add kgsecwoyamlall "kubectl get secret --watch -o=yaml --all-namespaces"
abbr --add kgnswoyamlall "kubectl get namespaces --watch -o=yaml --all-namespaces"
abbr --add kgwalloyaml "kubectl get --watch --all-namespaces -o=yaml"
abbr --add kgpowalloyaml "kubectl get pods --watch --all-namespaces -o=yaml"
abbr --add kgdepwalloyaml "kubectl get deployment --watch --all-namespaces -o=yaml"
abbr --add kgstswalloyaml "kubectl get statefulset --watch --all-namespaces -o=yaml"
abbr --add kgsvcwalloyaml "kubectl get service --watch --all-namespaces -o=yaml"
abbr --add kgingwalloyaml "kubectl get ingress --watch --all-namespaces -o=yaml"
abbr --add kgcmwalloyaml "kubectl get configmap --watch --all-namespaces -o=yaml"
abbr --add kgsecwalloyaml "kubectl get secret --watch --all-namespaces -o=yaml"
abbr --add kgnswalloyaml "kubectl get namespaces --watch --all-namespaces -o=yaml"
abbr --add kgowideallsl "kubectl get -o=wide --all-namespaces --show-labels"
abbr --add kgpoowideallsl "kubectl get pods -o=wide --all-namespaces --show-labels"
abbr --add kgdepowideallsl "kubectl get deployment -o=wide --all-namespaces --show-labels"
abbr --add kgstsowideallsl "kubectl get statefulset -o=wide --all-namespaces --show-labels"
abbr --add kgsvcowideallsl "kubectl get service -o=wide --all-namespaces --show-labels"
abbr --add kgingowideallsl "kubectl get ingress -o=wide --all-namespaces --show-labels"
abbr --add kgcmowideallsl "kubectl get configmap -o=wide --all-namespaces --show-labels"
abbr --add kgsecowideallsl "kubectl get secret -o=wide --all-namespaces --show-labels"
abbr --add kgnsowideallsl "kubectl get namespaces -o=wide --all-namespaces --show-labels"
abbr --add kgowideslall "kubectl get -o=wide --show-labels --all-namespaces"
abbr --add kgpoowideslall "kubectl get pods -o=wide --show-labels --all-namespaces"
abbr --add kgdepowideslall "kubectl get deployment -o=wide --show-labels --all-namespaces"
abbr --add kgstsowideslall "kubectl get statefulset -o=wide --show-labels --all-namespaces"
abbr --add kgsvcowideslall "kubectl get service -o=wide --show-labels --all-namespaces"
abbr --add kgingowideslall "kubectl get ingress -o=wide --show-labels --all-namespaces"
abbr --add kgcmowideslall "kubectl get configmap -o=wide --show-labels --all-namespaces"
abbr --add kgsecowideslall "kubectl get secret -o=wide --show-labels --all-namespaces"
abbr --add kgnsowideslall "kubectl get namespaces -o=wide --show-labels --all-namespaces"
abbr --add kgallowidesl "kubectl get --all-namespaces -o=wide --show-labels"
abbr --add kgpoallowidesl "kubectl get pods --all-namespaces -o=wide --show-labels"
abbr --add kgdepallowidesl "kubectl get deployment --all-namespaces -o=wide --show-labels"
abbr --add kgstsallowidesl "kubectl get statefulset --all-namespaces -o=wide --show-labels"
abbr --add kgsvcallowidesl "kubectl get service --all-namespaces -o=wide --show-labels"
abbr --add kgingallowidesl "kubectl get ingress --all-namespaces -o=wide --show-labels"
abbr --add kgcmallowidesl "kubectl get configmap --all-namespaces -o=wide --show-labels"
abbr --add kgsecallowidesl "kubectl get secret --all-namespaces -o=wide --show-labels"
abbr --add kgnsallowidesl "kubectl get namespaces --all-namespaces -o=wide --show-labels"
abbr --add kgallslowide "kubectl get --all-namespaces --show-labels -o=wide"
abbr --add kgpoallslowide "kubectl get pods --all-namespaces --show-labels -o=wide"
abbr --add kgdepallslowide "kubectl get deployment --all-namespaces --show-labels -o=wide"
abbr --add kgstsallslowide "kubectl get statefulset --all-namespaces --show-labels -o=wide"
abbr --add kgsvcallslowide "kubectl get service --all-namespaces --show-labels -o=wide"
abbr --add kgingallslowide "kubectl get ingress --all-namespaces --show-labels -o=wide"
abbr --add kgcmallslowide "kubectl get configmap --all-namespaces --show-labels -o=wide"
abbr --add kgsecallslowide "kubectl get secret --all-namespaces --show-labels -o=wide"
abbr --add kgnsallslowide "kubectl get namespaces --all-namespaces --show-labels -o=wide"
abbr --add kgslowideall "kubectl get --show-labels -o=wide --all-namespaces"
abbr --add kgposlowideall "kubectl get pods --show-labels -o=wide --all-namespaces"
abbr --add kgdepslowideall "kubectl get deployment --show-labels -o=wide --all-namespaces"
abbr --add kgstsslowideall "kubectl get statefulset --show-labels -o=wide --all-namespaces"
abbr --add kgsvcslowideall "kubectl get service --show-labels -o=wide --all-namespaces"
abbr --add kgingslowideall "kubectl get ingress --show-labels -o=wide --all-namespaces"
abbr --add kgcmslowideall "kubectl get configmap --show-labels -o=wide --all-namespaces"
abbr --add kgsecslowideall "kubectl get secret --show-labels -o=wide --all-namespaces"
abbr --add kgnsslowideall "kubectl get namespaces --show-labels -o=wide --all-namespaces"
abbr --add kgslallowide "kubectl get --show-labels --all-namespaces -o=wide"
abbr --add kgposlallowide "kubectl get pods --show-labels --all-namespaces -o=wide"
abbr --add kgdepslallowide "kubectl get deployment --show-labels --all-namespaces -o=wide"
abbr --add kgstsslallowide "kubectl get statefulset --show-labels --all-namespaces -o=wide"
abbr --add kgsvcslallowide "kubectl get service --show-labels --all-namespaces -o=wide"
abbr --add kgingslallowide "kubectl get ingress --show-labels --all-namespaces -o=wide"
abbr --add kgcmslallowide "kubectl get configmap --show-labels --all-namespaces -o=wide"
abbr --add kgsecslallowide "kubectl get secret --show-labels --all-namespaces -o=wide"
abbr --add kgnsslallowide "kubectl get namespaces --show-labels --all-namespaces -o=wide"
abbr --add kgallwowide "kubectl get --all-namespaces --watch -o=wide"
abbr --add kgpoallwowide "kubectl get pods --all-namespaces --watch -o=wide"
abbr --add kgdepallwowide "kubectl get deployment --all-namespaces --watch -o=wide"
abbr --add kgstsallwowide "kubectl get statefulset --all-namespaces --watch -o=wide"
abbr --add kgsvcallwowide "kubectl get service --all-namespaces --watch -o=wide"
abbr --add kgingallwowide "kubectl get ingress --all-namespaces --watch -o=wide"
abbr --add kgcmallwowide "kubectl get configmap --all-namespaces --watch -o=wide"
abbr --add kgsecallwowide "kubectl get secret --all-namespaces --watch -o=wide"
abbr --add kgnsallwowide "kubectl get namespaces --all-namespaces --watch -o=wide"
abbr --add kgwowideall "kubectl get --watch -o=wide --all-namespaces"
abbr --add kgpowowideall "kubectl get pods --watch -o=wide --all-namespaces"
abbr --add kgdepwowideall "kubectl get deployment --watch -o=wide --all-namespaces"
abbr --add kgstswowideall "kubectl get statefulset --watch -o=wide --all-namespaces"
abbr --add kgsvcwowideall "kubectl get service --watch -o=wide --all-namespaces"
abbr --add kgingwowideall "kubectl get ingress --watch -o=wide --all-namespaces"
abbr --add kgcmwowideall "kubectl get configmap --watch -o=wide --all-namespaces"
abbr --add kgsecwowideall "kubectl get secret --watch -o=wide --all-namespaces"
abbr --add kgnswowideall "kubectl get namespaces --watch -o=wide --all-namespaces"
abbr --add kgwallowide "kubectl get --watch --all-namespaces -o=wide"
abbr --add kgpowallowide "kubectl get pods --watch --all-namespaces -o=wide"
abbr --add kgdepwallowide "kubectl get deployment --watch --all-namespaces -o=wide"
abbr --add kgstswallowide "kubectl get statefulset --watch --all-namespaces -o=wide"
abbr --add kgsvcwallowide "kubectl get service --watch --all-namespaces -o=wide"
abbr --add kgingwallowide "kubectl get ingress --watch --all-namespaces -o=wide"
abbr --add kgcmwallowide "kubectl get configmap --watch --all-namespaces -o=wide"
abbr --add kgsecwallowide "kubectl get secret --watch --all-namespaces -o=wide"
abbr --add kgnswallowide "kubectl get namespaces --watch --all-namespaces -o=wide"
abbr --add kgslwowide "kubectl get --show-labels --watch -o=wide"
abbr --add ksysgslwowide "kubectl --namespace=kube-system get --show-labels --watch -o=wide"
abbr --add kgposlwowide "kubectl get pods --show-labels --watch -o=wide"
abbr --add ksysgposlwowide "kubectl --namespace=kube-system get pods --show-labels --watch -o=wide"
abbr --add kgdepslwowide "kubectl get deployment --show-labels --watch -o=wide"
abbr --add ksysgdepslwowide "kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide"
abbr --add kgstsslwowide "kubectl get statefulset --show-labels --watch -o=wide"
abbr --add ksysgstsslwowide "kubectl --namespace=kube-system get statefulset --show-labels --watch -o=wide"
abbr --add kgsvcslwowide "kubectl get service --show-labels --watch -o=wide"
abbr --add ksysgsvcslwowide "kubectl --namespace=kube-system get service --show-labels --watch -o=wide"
abbr --add kgingslwowide "kubectl get ingress --show-labels --watch -o=wide"
abbr --add ksysgingslwowide "kubectl --namespace=kube-system get ingress --show-labels --watch -o=wide"
abbr --add kgcmslwowide "kubectl get configmap --show-labels --watch -o=wide"
abbr --add ksysgcmslwowide "kubectl --namespace=kube-system get configmap --show-labels --watch -o=wide"
abbr --add kgsecslwowide "kubectl get secret --show-labels --watch -o=wide"
abbr --add ksysgsecslwowide "kubectl --namespace=kube-system get secret --show-labels --watch -o=wide"
abbr --add kgnoslwowide "kubectl get nodes --show-labels --watch -o=wide"
abbr --add kgnsslwowide "kubectl get namespaces --show-labels --watch -o=wide"
abbr --add kgwowidesl "kubectl get --watch -o=wide --show-labels"
abbr --add ksysgwowidesl "kubectl --namespace=kube-system get --watch -o=wide --show-labels"
abbr --add kgpowowidesl "kubectl get pods --watch -o=wide --show-labels"
abbr --add ksysgpowowidesl "kubectl --namespace=kube-system get pods --watch -o=wide --show-labels"
abbr --add kgdepwowidesl "kubectl get deployment --watch -o=wide --show-labels"
abbr --add ksysgdepwowidesl "kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels"
abbr --add kgstswowidesl "kubectl get statefulset --watch -o=wide --show-labels"
abbr --add ksysgstswowidesl "kubectl --namespace=kube-system get statefulset --watch -o=wide --show-labels"
abbr --add kgsvcwowidesl "kubectl get service --watch -o=wide --show-labels"
abbr --add ksysgsvcwowidesl "kubectl --namespace=kube-system get service --watch -o=wide --show-labels"
abbr --add kgingwowidesl "kubectl get ingress --watch -o=wide --show-labels"
abbr --add ksysgingwowidesl "kubectl --namespace=kube-system get ingress --watch -o=wide --show-labels"
abbr --add kgcmwowidesl "kubectl get configmap --watch -o=wide --show-labels"
abbr --add ksysgcmwowidesl "kubectl --namespace=kube-system get configmap --watch -o=wide --show-labels"
abbr --add kgsecwowidesl "kubectl get secret --watch -o=wide --show-labels"
abbr --add ksysgsecwowidesl "kubectl --namespace=kube-system get secret --watch -o=wide --show-labels"
abbr --add kgnowowidesl "kubectl get nodes --watch -o=wide --show-labels"
abbr --add kgnswowidesl "kubectl get namespaces --watch -o=wide --show-labels"
abbr --add kgwslowide "kubectl get --watch --show-labels -o=wide"
abbr --add ksysgwslowide "kubectl --namespace=kube-system get --watch --show-labels -o=wide"
abbr --add kgpowslowide "kubectl get pods --watch --show-labels -o=wide"
abbr --add ksysgpowslowide "kubectl --namespace=kube-system get pods --watch --show-labels -o=wide"
abbr --add kgdepwslowide "kubectl get deployment --watch --show-labels -o=wide"
abbr --add ksysgdepwslowide "kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide"
abbr --add kgstswslowide "kubectl get statefulset --watch --show-labels -o=wide"
abbr --add ksysgstswslowide "kubectl --namespace=kube-system get statefulset --watch --show-labels -o=wide"
abbr --add kgsvcwslowide "kubectl get service --watch --show-labels -o=wide"
abbr --add ksysgsvcwslowide "kubectl --namespace=kube-system get service --watch --show-labels -o=wide"
abbr --add kgingwslowide "kubectl get ingress --watch --show-labels -o=wide"
abbr --add ksysgingwslowide "kubectl --namespace=kube-system get ingress --watch --show-labels -o=wide"
abbr --add kgcmwslowide "kubectl get configmap --watch --show-labels -o=wide"
abbr --add ksysgcmwslowide "kubectl --namespace=kube-system get configmap --watch --show-labels -o=wide"
abbr --add kgsecwslowide "kubectl get secret --watch --show-labels -o=wide"
abbr --add ksysgsecwslowide "kubectl --namespace=kube-system get secret --watch --show-labels -o=wide"
abbr --add kgnowslowide "kubectl get nodes --watch --show-labels -o=wide"
abbr --add kgnswslowide "kubectl get namespaces --watch --show-labels -o=wide"
abbr --add kgallwojson "kubectl get --all-namespaces --watch -o=json"
abbr --add kgpoallwojson "kubectl get pods --all-namespaces --watch -o=json"
abbr --add kgdepallwojson "kubectl get deployment --all-namespaces --watch -o=json"
abbr --add kgstsallwojson "kubectl get statefulset --all-namespaces --watch -o=json"
abbr --add kgsvcallwojson "kubectl get service --all-namespaces --watch -o=json"
abbr --add kgingallwojson "kubectl get ingress --all-namespaces --watch -o=json"
abbr --add kgcmallwojson "kubectl get configmap --all-namespaces --watch -o=json"
abbr --add kgsecallwojson "kubectl get secret --all-namespaces --watch -o=json"
abbr --add kgnsallwojson "kubectl get namespaces --all-namespaces --watch -o=json"
abbr --add kgwojsonall "kubectl get --watch -o=json --all-namespaces"
abbr --add kgpowojsonall "kubectl get pods --watch -o=json --all-namespaces"
abbr --add kgdepwojsonall "kubectl get deployment --watch -o=json --all-namespaces"
abbr --add kgstswojsonall "kubectl get statefulset --watch -o=json --all-namespaces"
abbr --add kgsvcwojsonall "kubectl get service --watch -o=json --all-namespaces"
abbr --add kgingwojsonall "kubectl get ingress --watch -o=json --all-namespaces"
abbr --add kgcmwojsonall "kubectl get configmap --watch -o=json --all-namespaces"
abbr --add kgsecwojsonall "kubectl get secret --watch -o=json --all-namespaces"
abbr --add kgnswojsonall "kubectl get namespaces --watch -o=json --all-namespaces"
abbr --add kgwallojson "kubectl get --watch --all-namespaces -o=json"
abbr --add kgpowallojson "kubectl get pods --watch --all-namespaces -o=json"
abbr --add kgdepwallojson "kubectl get deployment --watch --all-namespaces -o=json"
abbr --add kgstswallojson "kubectl get statefulset --watch --all-namespaces -o=json"
abbr --add kgsvcwallojson "kubectl get service --watch --all-namespaces -o=json"
abbr --add kgingwallojson "kubectl get ingress --watch --all-namespaces -o=json"
abbr --add kgcmwallojson "kubectl get configmap --watch --all-namespaces -o=json"
abbr --add kgsecwallojson "kubectl get secret --watch --all-namespaces -o=json"
abbr --add kgnswallojson "kubectl get namespaces --watch --all-namespaces -o=json"
abbr --add kgallslw "kubectl get --all-namespaces --show-labels --watch"
abbr --add kgpoallslw "kubectl get pods --all-namespaces --show-labels --watch"
abbr --add kgdepallslw "kubectl get deployment --all-namespaces --show-labels --watch"
abbr --add kgstsallslw "kubectl get statefulset --all-namespaces --show-labels --watch"
abbr --add kgsvcallslw "kubectl get service --all-namespaces --show-labels --watch"
abbr --add kgingallslw "kubectl get ingress --all-namespaces --show-labels --watch"
abbr --add kgcmallslw "kubectl get configmap --all-namespaces --show-labels --watch"
abbr --add kgsecallslw "kubectl get secret --all-namespaces --show-labels --watch"
abbr --add kgnsallslw "kubectl get namespaces --all-namespaces --show-labels --watch"
abbr --add kgallwsl "kubectl get --all-namespaces --watch --show-labels"
abbr --add kgpoallwsl "kubectl get pods --all-namespaces --watch --show-labels"
abbr --add kgdepallwsl "kubectl get deployment --all-namespaces --watch --show-labels"
abbr --add kgstsallwsl "kubectl get statefulset --all-namespaces --watch --show-labels"
abbr --add kgsvcallwsl "kubectl get service --all-namespaces --watch --show-labels"
abbr --add kgingallwsl "kubectl get ingress --all-namespaces --watch --show-labels"
abbr --add kgcmallwsl "kubectl get configmap --all-namespaces --watch --show-labels"
abbr --add kgsecallwsl "kubectl get secret --all-namespaces --watch --show-labels"
abbr --add kgnsallwsl "kubectl get namespaces --all-namespaces --watch --show-labels"
abbr --add kgslallw "kubectl get --show-labels --all-namespaces --watch"
abbr --add kgposlallw "kubectl get pods --show-labels --all-namespaces --watch"
abbr --add kgdepslallw "kubectl get deployment --show-labels --all-namespaces --watch"
abbr --add kgstsslallw "kubectl get statefulset --show-labels --all-namespaces --watch"
abbr --add kgsvcslallw "kubectl get service --show-labels --all-namespaces --watch"
abbr --add kgingslallw "kubectl get ingress --show-labels --all-namespaces --watch"
abbr --add kgcmslallw "kubectl get configmap --show-labels --all-namespaces --watch"
abbr --add kgsecslallw "kubectl get secret --show-labels --all-namespaces --watch"
abbr --add kgnsslallw "kubectl get namespaces --show-labels --all-namespaces --watch"
abbr --add kgslwall "kubectl get --show-labels --watch --all-namespaces"
abbr --add kgposlwall "kubectl get pods --show-labels --watch --all-namespaces"
abbr --add kgdepslwall "kubectl get deployment --show-labels --watch --all-namespaces"
abbr --add kgstsslwall "kubectl get statefulset --show-labels --watch --all-namespaces"
abbr --add kgsvcslwall "kubectl get service --show-labels --watch --all-namespaces"
abbr --add kgingslwall "kubectl get ingress --show-labels --watch --all-namespaces"
abbr --add kgcmslwall "kubectl get configmap --show-labels --watch --all-namespaces"
abbr --add kgsecslwall "kubectl get secret --show-labels --watch --all-namespaces"
abbr --add kgnsslwall "kubectl get namespaces --show-labels --watch --all-namespaces"
abbr --add kgwallsl "kubectl get --watch --all-namespaces --show-labels"
abbr --add kgpowallsl "kubectl get pods --watch --all-namespaces --show-labels"
abbr --add kgdepwallsl "kubectl get deployment --watch --all-namespaces --show-labels"
abbr --add kgstswallsl "kubectl get statefulset --watch --all-namespaces --show-labels"
abbr --add kgsvcwallsl "kubectl get service --watch --all-namespaces --show-labels"
abbr --add kgingwallsl "kubectl get ingress --watch --all-namespaces --show-labels"
abbr --add kgcmwallsl "kubectl get configmap --watch --all-namespaces --show-labels"
abbr --add kgsecwallsl "kubectl get secret --watch --all-namespaces --show-labels"
abbr --add kgnswallsl "kubectl get namespaces --watch --all-namespaces --show-labels"
abbr --add kgwslall "kubectl get --watch --show-labels --all-namespaces"
abbr --add kgpowslall "kubectl get pods --watch --show-labels --all-namespaces"
abbr --add kgdepwslall "kubectl get deployment --watch --show-labels --all-namespaces"
abbr --add kgstswslall "kubectl get statefulset --watch --show-labels --all-namespaces"
abbr --add kgsvcwslall "kubectl get service --watch --show-labels --all-namespaces"
abbr --add kgingwslall "kubectl get ingress --watch --show-labels --all-namespaces"
abbr --add kgcmwslall "kubectl get configmap --watch --show-labels --all-namespaces"
abbr --add kgsecwslall "kubectl get secret --watch --show-labels --all-namespaces"
abbr --add kgnswslall "kubectl get namespaces --watch --show-labels --all-namespaces"
abbr --add kgallslwowide "kubectl get --all-namespaces --show-labels --watch -o=wide"
abbr --add kgpoallslwowide "kubectl get pods --all-namespaces --show-labels --watch -o=wide"
abbr --add kgdepallslwowide "kubectl get deployment --all-namespaces --show-labels --watch -o=wide"
abbr --add kgstsallslwowide "kubectl get statefulset --all-namespaces --show-labels --watch -o=wide"
abbr --add kgsvcallslwowide "kubectl get service --all-namespaces --show-labels --watch -o=wide"
abbr --add kgingallslwowide "kubectl get ingress --all-namespaces --show-labels --watch -o=wide"
abbr --add kgcmallslwowide "kubectl get configmap --all-namespaces --show-labels --watch -o=wide"
abbr --add kgsecallslwowide "kubectl get secret --all-namespaces --show-labels --watch -o=wide"
abbr --add kgnsallslwowide "kubectl get namespaces --all-namespaces --show-labels --watch -o=wide"
abbr --add kgallwowidesl "kubectl get --all-namespaces --watch -o=wide --show-labels"
abbr --add kgpoallwowidesl "kubectl get pods --all-namespaces --watch -o=wide --show-labels"
abbr --add kgdepallwowidesl "kubectl get deployment --all-namespaces --watch -o=wide --show-labels"
abbr --add kgstsallwowidesl "kubectl get statefulset --all-namespaces --watch -o=wide --show-labels"
abbr --add kgsvcallwowidesl "kubectl get service --all-namespaces --watch -o=wide --show-labels"
abbr --add kgingallwowidesl "kubectl get ingress --all-namespaces --watch -o=wide --show-labels"
abbr --add kgcmallwowidesl "kubectl get configmap --all-namespaces --watch -o=wide --show-labels"
abbr --add kgsecallwowidesl "kubectl get secret --all-namespaces --watch -o=wide --show-labels"
abbr --add kgnsallwowidesl "kubectl get namespaces --all-namespaces --watch -o=wide --show-labels"
abbr --add kgallwslowide "kubectl get --all-namespaces --watch --show-labels -o=wide"
abbr --add kgpoallwslowide "kubectl get pods --all-namespaces --watch --show-labels -o=wide"
abbr --add kgdepallwslowide "kubectl get deployment --all-namespaces --watch --show-labels -o=wide"
abbr --add kgstsallwslowide "kubectl get statefulset --all-namespaces --watch --show-labels -o=wide"
abbr --add kgsvcallwslowide "kubectl get service --all-namespaces --watch --show-labels -o=wide"
abbr --add kgingallwslowide "kubectl get ingress --all-namespaces --watch --show-labels -o=wide"
abbr --add kgcmallwslowide "kubectl get configmap --all-namespaces --watch --show-labels -o=wide"
abbr --add kgsecallwslowide "kubectl get secret --all-namespaces --watch --show-labels -o=wide"
abbr --add kgnsallwslowide "kubectl get namespaces --all-namespaces --watch --show-labels -o=wide"
abbr --add kgslallwowide "kubectl get --show-labels --all-namespaces --watch -o=wide"
abbr --add kgposlallwowide "kubectl get pods --show-labels --all-namespaces --watch -o=wide"
abbr --add kgdepslallwowide "kubectl get deployment --show-labels --all-namespaces --watch -o=wide"
abbr --add kgstsslallwowide "kubectl get statefulset --show-labels --all-namespaces --watch -o=wide"
abbr --add kgsvcslallwowide "kubectl get service --show-labels --all-namespaces --watch -o=wide"
abbr --add kgingslallwowide "kubectl get ingress --show-labels --all-namespaces --watch -o=wide"
abbr --add kgcmslallwowide "kubectl get configmap --show-labels --all-namespaces --watch -o=wide"
abbr --add kgsecslallwowide "kubectl get secret --show-labels --all-namespaces --watch -o=wide"
abbr --add kgnsslallwowide "kubectl get namespaces --show-labels --all-namespaces --watch -o=wide"
abbr --add kgslwowideall "kubectl get --show-labels --watch -o=wide --all-namespaces"
abbr --add kgposlwowideall "kubectl get pods --show-labels --watch -o=wide --all-namespaces"
abbr --add kgdepslwowideall "kubectl get deployment --show-labels --watch -o=wide --all-namespaces"
abbr --add kgstsslwowideall "kubectl get statefulset --show-labels --watch -o=wide --all-namespaces"
abbr --add kgsvcslwowideall "kubectl get service --show-labels --watch -o=wide --all-namespaces"
abbr --add kgingslwowideall "kubectl get ingress --show-labels --watch -o=wide --all-namespaces"
abbr --add kgcmslwowideall "kubectl get configmap --show-labels --watch -o=wide --all-namespaces"
abbr --add kgsecslwowideall "kubectl get secret --show-labels --watch -o=wide --all-namespaces"
abbr --add kgnsslwowideall "kubectl get namespaces --show-labels --watch -o=wide --all-namespaces"
abbr --add kgslwallowide "kubectl get --show-labels --watch --all-namespaces -o=wide"
abbr --add kgposlwallowide "kubectl get pods --show-labels --watch --all-namespaces -o=wide"
abbr --add kgdepslwallowide "kubectl get deployment --show-labels --watch --all-namespaces -o=wide"
abbr --add kgstsslwallowide "kubectl get statefulset --show-labels --watch --all-namespaces -o=wide"
abbr --add kgsvcslwallowide "kubectl get service --show-labels --watch --all-namespaces -o=wide"
abbr --add kgingslwallowide "kubectl get ingress --show-labels --watch --all-namespaces -o=wide"
abbr --add kgcmslwallowide "kubectl get configmap --show-labels --watch --all-namespaces -o=wide"
abbr --add kgsecslwallowide "kubectl get secret --show-labels --watch --all-namespaces -o=wide"
abbr --add kgnsslwallowide "kubectl get namespaces --show-labels --watch --all-namespaces -o=wide"
abbr --add kgwowideallsl "kubectl get --watch -o=wide --all-namespaces --show-labels"
abbr --add kgpowowideallsl "kubectl get pods --watch -o=wide --all-namespaces --show-labels"
abbr --add kgdepwowideallsl "kubectl get deployment --watch -o=wide --all-namespaces --show-labels"
abbr --add kgstswowideallsl "kubectl get statefulset --watch -o=wide --all-namespaces --show-labels"
abbr --add kgsvcwowideallsl "kubectl get service --watch -o=wide --all-namespaces --show-labels"
abbr --add kgingwowideallsl "kubectl get ingress --watch -o=wide --all-namespaces --show-labels"
abbr --add kgcmwowideallsl "kubectl get configmap --watch -o=wide --all-namespaces --show-labels"
abbr --add kgsecwowideallsl "kubectl get secret --watch -o=wide --all-namespaces --show-labels"
abbr --add kgnswowideallsl "kubectl get namespaces --watch -o=wide --all-namespaces --show-labels"
abbr --add kgwowideslall "kubectl get --watch -o=wide --show-labels --all-namespaces"
abbr --add kgpowowideslall "kubectl get pods --watch -o=wide --show-labels --all-namespaces"
abbr --add kgdepwowideslall "kubectl get deployment --watch -o=wide --show-labels --all-namespaces"
abbr --add kgstswowideslall "kubectl get statefulset --watch -o=wide --show-labels --all-namespaces"
abbr --add kgsvcwowideslall "kubectl get service --watch -o=wide --show-labels --all-namespaces"
abbr --add kgingwowideslall "kubectl get ingress --watch -o=wide --show-labels --all-namespaces"
abbr --add kgcmwowideslall "kubectl get configmap --watch -o=wide --show-labels --all-namespaces"
abbr --add kgsecwowideslall "kubectl get secret --watch -o=wide --show-labels --all-namespaces"
abbr --add kgnswowideslall "kubectl get namespaces --watch -o=wide --show-labels --all-namespaces"
abbr --add kgwallowidesl "kubectl get --watch --all-namespaces -o=wide --show-labels"
abbr --add kgpowallowidesl "kubectl get pods --watch --all-namespaces -o=wide --show-labels"
abbr --add kgdepwallowidesl "kubectl get deployment --watch --all-namespaces -o=wide --show-labels"
abbr --add kgstswallowidesl "kubectl get statefulset --watch --all-namespaces -o=wide --show-labels"
abbr --add kgsvcwallowidesl "kubectl get service --watch --all-namespaces -o=wide --show-labels"
abbr --add kgingwallowidesl "kubectl get ingress --watch --all-namespaces -o=wide --show-labels"
abbr --add kgcmwallowidesl "kubectl get configmap --watch --all-namespaces -o=wide --show-labels"
abbr --add kgsecwallowidesl "kubectl get secret --watch --all-namespaces -o=wide --show-labels"
abbr --add kgnswallowidesl "kubectl get namespaces --watch --all-namespaces -o=wide --show-labels"
abbr --add kgwallslowide "kubectl get --watch --all-namespaces --show-labels -o=wide"
abbr --add kgpowallslowide "kubectl get pods --watch --all-namespaces --show-labels -o=wide"
abbr --add kgdepwallslowide "kubectl get deployment --watch --all-namespaces --show-labels -o=wide"
abbr --add kgstswallslowide "kubectl get statefulset --watch --all-namespaces --show-labels -o=wide"
abbr --add kgsvcwallslowide "kubectl get service --watch --all-namespaces --show-labels -o=wide"
abbr --add kgingwallslowide "kubectl get ingress --watch --all-namespaces --show-labels -o=wide"
abbr --add kgcmwallslowide "kubectl get configmap --watch --all-namespaces --show-labels -o=wide"
abbr --add kgsecwallslowide "kubectl get secret --watch --all-namespaces --show-labels -o=wide"
abbr --add kgnswallslowide "kubectl get namespaces --watch --all-namespaces --show-labels -o=wide"
abbr --add kgwslowideall "kubectl get --watch --show-labels -o=wide --all-namespaces"
abbr --add kgpowslowideall "kubectl get pods --watch --show-labels -o=wide --all-namespaces"
abbr --add kgdepwslowideall "kubectl get deployment --watch --show-labels -o=wide --all-namespaces"
abbr --add kgstswslowideall "kubectl get statefulset --watch --show-labels -o=wide --all-namespaces"
abbr --add kgsvcwslowideall "kubectl get service --watch --show-labels -o=wide --all-namespaces"
abbr --add kgingwslowideall "kubectl get ingress --watch --show-labels -o=wide --all-namespaces"
abbr --add kgcmwslowideall "kubectl get configmap --watch --show-labels -o=wide --all-namespaces"
abbr --add kgsecwslowideall "kubectl get secret --watch --show-labels -o=wide --all-namespaces"
abbr --add kgnswslowideall "kubectl get namespaces --watch --show-labels -o=wide --all-namespaces"
abbr --add kgwslallowide "kubectl get --watch --show-labels --all-namespaces -o=wide"
abbr --add kgpowslallowide "kubectl get pods --watch --show-labels --all-namespaces -o=wide"
abbr --add kgdepwslallowide "kubectl get deployment --watch --show-labels --all-namespaces -o=wide"
abbr --add kgstswslallowide "kubectl get statefulset --watch --show-labels --all-namespaces -o=wide"
abbr --add kgsvcwslallowide "kubectl get service --watch --show-labels --all-namespaces -o=wide"
abbr --add kgingwslallowide "kubectl get ingress --watch --show-labels --all-namespaces -o=wide"
abbr --add kgcmwslallowide "kubectl get configmap --watch --show-labels --all-namespaces -o=wide"
abbr --add kgsecwslallowide "kubectl get secret --watch --show-labels --all-namespaces -o=wide"
abbr --add kgnswslallowide "kubectl get namespaces --watch --show-labels --all-namespaces -o=wide"
abbr --add kgf "kubectl get --recursive -f"
abbr --add kdf "kubectl describe --recursive -f"
abbr --add krmf "kubectl delete --recursive -f"
abbr --add kgoyamlf "kubectl get -o=yaml --recursive -f"
abbr --add kgowidef "kubectl get -o=wide --recursive -f"
abbr --add kgojsonf "kubectl get -o=json --recursive -f"
abbr --add kgslf "kubectl get --show-labels --recursive -f"
abbr --add kgwf "kubectl get --watch --recursive -f"
abbr --add kgwoyamlf "kubectl get --watch -o=yaml --recursive -f"
abbr --add kgowideslf "kubectl get -o=wide --show-labels --recursive -f"
abbr --add kgslowidef "kubectl get --show-labels -o=wide --recursive -f"
abbr --add kgwowidef "kubectl get --watch -o=wide --recursive -f"
abbr --add kgwojsonf "kubectl get --watch -o=json --recursive -f"
abbr --add kgslwf "kubectl get --show-labels --watch --recursive -f"
abbr --add kgwslf "kubectl get --watch --show-labels --recursive -f"
abbr --add kgslwowidef "kubectl get --show-labels --watch -o=wide --recursive -f"
abbr --add kgwowideslf "kubectl get --watch -o=wide --show-labels --recursive -f"
abbr --add kgwslowidef "kubectl get --watch --show-labels -o=wide --recursive -f"
abbr --add kgl "kubectl get -l"
abbr --add ksysgl "kubectl --namespace=kube-system get -l"
abbr --add kdl "kubectl describe -l"
abbr --add ksysdl "kubectl --namespace=kube-system describe -l"
abbr --add krml "kubectl delete -l"
abbr --add ksysrml "kubectl --namespace=kube-system delete -l"
abbr --add kgpol "kubectl get pods -l"
abbr --add ksysgpol "kubectl --namespace=kube-system get pods -l"
abbr --add kdpol "kubectl describe pods -l"
abbr --add ksysdpol "kubectl --namespace=kube-system describe pods -l"
abbr --add krmpol "kubectl delete pods -l"
abbr --add ksysrmpol "kubectl --namespace=kube-system delete pods -l"
abbr --add kgdepl "kubectl get deployment -l"
abbr --add ksysgdepl "kubectl --namespace=kube-system get deployment -l"
abbr --add kddepl "kubectl describe deployment -l"
abbr --add ksysddepl "kubectl --namespace=kube-system describe deployment -l"
abbr --add krmdepl "kubectl delete deployment -l"
abbr --add ksysrmdepl "kubectl --namespace=kube-system delete deployment -l"
abbr --add kgstsl "kubectl get statefulset -l"
abbr --add ksysgstsl "kubectl --namespace=kube-system get statefulset -l"
abbr --add kdstsl "kubectl describe statefulset -l"
abbr --add ksysdstsl "kubectl --namespace=kube-system describe statefulset -l"
abbr --add krmstsl "kubectl delete statefulset -l"
abbr --add ksysrmstsl "kubectl --namespace=kube-system delete statefulset -l"
abbr --add kgsvcl "kubectl get service -l"
abbr --add ksysgsvcl "kubectl --namespace=kube-system get service -l"
abbr --add kdsvcl "kubectl describe service -l"
abbr --add ksysdsvcl "kubectl --namespace=kube-system describe service -l"
abbr --add krmsvcl "kubectl delete service -l"
abbr --add ksysrmsvcl "kubectl --namespace=kube-system delete service -l"
abbr --add kgingl "kubectl get ingress -l"
abbr --add ksysgingl "kubectl --namespace=kube-system get ingress -l"
abbr --add kdingl "kubectl describe ingress -l"
abbr --add ksysdingl "kubectl --namespace=kube-system describe ingress -l"
abbr --add krmingl "kubectl delete ingress -l"
abbr --add ksysrmingl "kubectl --namespace=kube-system delete ingress -l"
abbr --add kgcml "kubectl get configmap -l"
abbr --add ksysgcml "kubectl --namespace=kube-system get configmap -l"
abbr --add kdcml "kubectl describe configmap -l"
abbr --add ksysdcml "kubectl --namespace=kube-system describe configmap -l"
abbr --add krmcml "kubectl delete configmap -l"
abbr --add ksysrmcml "kubectl --namespace=kube-system delete configmap -l"
abbr --add kgsecl "kubectl get secret -l"
abbr --add ksysgsecl "kubectl --namespace=kube-system get secret -l"
abbr --add kdsecl "kubectl describe secret -l"
abbr --add ksysdsecl "kubectl --namespace=kube-system describe secret -l"
abbr --add krmsecl "kubectl delete secret -l"
abbr --add ksysrmsecl "kubectl --namespace=kube-system delete secret -l"
abbr --add kgnol "kubectl get nodes -l"
abbr --add kdnol "kubectl describe nodes -l"
abbr --add kgnsl "kubectl get namespaces -l"
abbr --add kdnsl "kubectl describe namespaces -l"
abbr --add krmnsl "kubectl delete namespaces -l"
abbr --add kgoyamll "kubectl get -o=yaml -l"
abbr --add ksysgoyamll "kubectl --namespace=kube-system get -o=yaml -l"
abbr --add kgpooyamll "kubectl get pods -o=yaml -l"
abbr --add ksysgpooyamll "kubectl --namespace=kube-system get pods -o=yaml -l"
abbr --add kgdepoyamll "kubectl get deployment -o=yaml -l"
abbr --add ksysgdepoyamll "kubectl --namespace=kube-system get deployment -o=yaml -l"
abbr --add kgstsoyamll "kubectl get statefulset -o=yaml -l"
abbr --add ksysgstsoyamll "kubectl --namespace=kube-system get statefulset -o=yaml -l"
abbr --add kgsvcoyamll "kubectl get service -o=yaml -l"
abbr --add ksysgsvcoyamll "kubectl --namespace=kube-system get service -o=yaml -l"
abbr --add kgingoyamll "kubectl get ingress -o=yaml -l"
abbr --add ksysgingoyamll "kubectl --namespace=kube-system get ingress -o=yaml -l"
abbr --add kgcmoyamll "kubectl get configmap -o=yaml -l"
abbr --add ksysgcmoyamll "kubectl --namespace=kube-system get configmap -o=yaml -l"
abbr --add kgsecoyamll "kubectl get secret -o=yaml -l"
abbr --add ksysgsecoyamll "kubectl --namespace=kube-system get secret -o=yaml -l"
abbr --add kgnooyamll "kubectl get nodes -o=yaml -l"
abbr --add kgnsoyamll "kubectl get namespaces -o=yaml -l"
abbr --add kgowidel "kubectl get -o=wide -l"
abbr --add ksysgowidel "kubectl --namespace=kube-system get -o=wide -l"
abbr --add kgpoowidel "kubectl get pods -o=wide -l"
abbr --add ksysgpoowidel "kubectl --namespace=kube-system get pods -o=wide -l"
abbr --add kgdepowidel "kubectl get deployment -o=wide -l"
abbr --add ksysgdepowidel "kubectl --namespace=kube-system get deployment -o=wide -l"
abbr --add kgstsowidel "kubectl get statefulset -o=wide -l"
abbr --add ksysgstsowidel "kubectl --namespace=kube-system get statefulset -o=wide -l"
abbr --add kgsvcowidel "kubectl get service -o=wide -l"
abbr --add ksysgsvcowidel "kubectl --namespace=kube-system get service -o=wide -l"
abbr --add kgingowidel "kubectl get ingress -o=wide -l"
abbr --add ksysgingowidel "kubectl --namespace=kube-system get ingress -o=wide -l"
abbr --add kgcmowidel "kubectl get configmap -o=wide -l"
abbr --add ksysgcmowidel "kubectl --namespace=kube-system get configmap -o=wide -l"
abbr --add kgsecowidel "kubectl get secret -o=wide -l"
abbr --add ksysgsecowidel "kubectl --namespace=kube-system get secret -o=wide -l"
abbr --add kgnoowidel "kubectl get nodes -o=wide -l"
abbr --add kgnsowidel "kubectl get namespaces -o=wide -l"
abbr --add kgojsonl "kubectl get -o=json -l"
abbr --add ksysgojsonl "kubectl --namespace=kube-system get -o=json -l"
abbr --add kgpoojsonl "kubectl get pods -o=json -l"
abbr --add ksysgpoojsonl "kubectl --namespace=kube-system get pods -o=json -l"
abbr --add kgdepojsonl "kubectl get deployment -o=json -l"
abbr --add ksysgdepojsonl "kubectl --namespace=kube-system get deployment -o=json -l"
abbr --add kgstsojsonl "kubectl get statefulset -o=json -l"
abbr --add ksysgstsojsonl "kubectl --namespace=kube-system get statefulset -o=json -l"
abbr --add kgsvcojsonl "kubectl get service -o=json -l"
abbr --add ksysgsvcojsonl "kubectl --namespace=kube-system get service -o=json -l"
abbr --add kgingojsonl "kubectl get ingress -o=json -l"
abbr --add ksysgingojsonl "kubectl --namespace=kube-system get ingress -o=json -l"
abbr --add kgcmojsonl "kubectl get configmap -o=json -l"
abbr --add ksysgcmojsonl "kubectl --namespace=kube-system get configmap -o=json -l"
abbr --add kgsecojsonl "kubectl get secret -o=json -l"
abbr --add ksysgsecojsonl "kubectl --namespace=kube-system get secret -o=json -l"
abbr --add kgnoojsonl "kubectl get nodes -o=json -l"
abbr --add kgnsojsonl "kubectl get namespaces -o=json -l"
abbr --add kgsll "kubectl get --show-labels -l"
abbr --add ksysgsll "kubectl --namespace=kube-system get --show-labels -l"
abbr --add kgposll "kubectl get pods --show-labels -l"
abbr --add ksysgposll "kubectl --namespace=kube-system get pods --show-labels -l"
abbr --add kgdepsll "kubectl get deployment --show-labels -l"
abbr --add ksysgdepsll "kubectl --namespace=kube-system get deployment --show-labels -l"
abbr --add kgstssll "kubectl get statefulset --show-labels -l"
abbr --add ksysgstssll "kubectl --namespace=kube-system get statefulset --show-labels -l"
abbr --add kgsvcsll "kubectl get service --show-labels -l"
abbr --add ksysgsvcsll "kubectl --namespace=kube-system get service --show-labels -l"
abbr --add kgingsll "kubectl get ingress --show-labels -l"
abbr --add ksysgingsll "kubectl --namespace=kube-system get ingress --show-labels -l"
abbr --add kgcmsll "kubectl get configmap --show-labels -l"
abbr --add ksysgcmsll "kubectl --namespace=kube-system get configmap --show-labels -l"
abbr --add kgsecsll "kubectl get secret --show-labels -l"
abbr --add ksysgsecsll "kubectl --namespace=kube-system get secret --show-labels -l"
abbr --add kgnosll "kubectl get nodes --show-labels -l"
abbr --add kgnssll "kubectl get namespaces --show-labels -l"
abbr --add kgwl "kubectl get --watch -l"
abbr --add ksysgwl "kubectl --namespace=kube-system get --watch -l"
abbr --add kgpowl "kubectl get pods --watch -l"
abbr --add ksysgpowl "kubectl --namespace=kube-system get pods --watch -l"
abbr --add kgdepwl "kubectl get deployment --watch -l"
abbr --add ksysgdepwl "kubectl --namespace=kube-system get deployment --watch -l"
abbr --add kgstswl "kubectl get statefulset --watch -l"
abbr --add ksysgstswl "kubectl --namespace=kube-system get statefulset --watch -l"
abbr --add kgsvcwl "kubectl get service --watch -l"
abbr --add ksysgsvcwl "kubectl --namespace=kube-system get service --watch -l"
abbr --add kgingwl "kubectl get ingress --watch -l"
abbr --add ksysgingwl "kubectl --namespace=kube-system get ingress --watch -l"
abbr --add kgcmwl "kubectl get configmap --watch -l"
abbr --add ksysgcmwl "kubectl --namespace=kube-system get configmap --watch -l"
abbr --add kgsecwl "kubectl get secret --watch -l"
abbr --add ksysgsecwl "kubectl --namespace=kube-system get secret --watch -l"
abbr --add kgnowl "kubectl get nodes --watch -l"
abbr --add kgnswl "kubectl get namespaces --watch -l"
abbr --add kgwoyamll "kubectl get --watch -o=yaml -l"
abbr --add ksysgwoyamll "kubectl --namespace=kube-system get --watch -o=yaml -l"
abbr --add kgpowoyamll "kubectl get pods --watch -o=yaml -l"
abbr --add ksysgpowoyamll "kubectl --namespace=kube-system get pods --watch -o=yaml -l"
abbr --add kgdepwoyamll "kubectl get deployment --watch -o=yaml -l"
abbr --add ksysgdepwoyamll "kubectl --namespace=kube-system get deployment --watch -o=yaml -l"
abbr --add kgstswoyamll "kubectl get statefulset --watch -o=yaml -l"
abbr --add ksysgstswoyamll "kubectl --namespace=kube-system get statefulset --watch -o=yaml -l"
abbr --add kgsvcwoyamll "kubectl get service --watch -o=yaml -l"
abbr --add ksysgsvcwoyamll "kubectl --namespace=kube-system get service --watch -o=yaml -l"
abbr --add kgingwoyamll "kubectl get ingress --watch -o=yaml -l"
abbr --add ksysgingwoyamll "kubectl --namespace=kube-system get ingress --watch -o=yaml -l"
abbr --add kgcmwoyamll "kubectl get configmap --watch -o=yaml -l"
abbr --add ksysgcmwoyamll "kubectl --namespace=kube-system get configmap --watch -o=yaml -l"
abbr --add kgsecwoyamll "kubectl get secret --watch -o=yaml -l"
abbr --add ksysgsecwoyamll "kubectl --namespace=kube-system get secret --watch -o=yaml -l"
abbr --add kgnowoyamll "kubectl get nodes --watch -o=yaml -l"
abbr --add kgnswoyamll "kubectl get namespaces --watch -o=yaml -l"
abbr --add kgowidesll "kubectl get -o=wide --show-labels -l"
abbr --add ksysgowidesll "kubectl --namespace=kube-system get -o=wide --show-labels -l"
abbr --add kgpoowidesll "kubectl get pods -o=wide --show-labels -l"
abbr --add ksysgpoowidesll "kubectl --namespace=kube-system get pods -o=wide --show-labels -l"
abbr --add kgdepowidesll "kubectl get deployment -o=wide --show-labels -l"
abbr --add ksysgdepowidesll "kubectl --namespace=kube-system get deployment -o=wide --show-labels -l"
abbr --add kgstsowidesll "kubectl get statefulset -o=wide --show-labels -l"
abbr --add ksysgstsowidesll "kubectl --namespace=kube-system get statefulset -o=wide --show-labels -l"
abbr --add kgsvcowidesll "kubectl get service -o=wide --show-labels -l"
abbr --add ksysgsvcowidesll "kubectl --namespace=kube-system get service -o=wide --show-labels -l"
abbr --add kgingowidesll "kubectl get ingress -o=wide --show-labels -l"
abbr --add ksysgingowidesll "kubectl --namespace=kube-system get ingress -o=wide --show-labels -l"
abbr --add kgcmowidesll "kubectl get configmap -o=wide --show-labels -l"
abbr --add ksysgcmowidesll "kubectl --namespace=kube-system get configmap -o=wide --show-labels -l"
abbr --add kgsecowidesll "kubectl get secret -o=wide --show-labels -l"
abbr --add ksysgsecowidesll "kubectl --namespace=kube-system get secret -o=wide --show-labels -l"
abbr --add kgnoowidesll "kubectl get nodes -o=wide --show-labels -l"
abbr --add kgnsowidesll "kubectl get namespaces -o=wide --show-labels -l"
abbr --add kgslowidel "kubectl get --show-labels -o=wide -l"
abbr --add ksysgslowidel "kubectl --namespace=kube-system get --show-labels -o=wide -l"
abbr --add kgposlowidel "kubectl get pods --show-labels -o=wide -l"
abbr --add ksysgposlowidel "kubectl --namespace=kube-system get pods --show-labels -o=wide -l"
abbr --add kgdepslowidel "kubectl get deployment --show-labels -o=wide -l"
abbr --add ksysgdepslowidel "kubectl --namespace=kube-system get deployment --show-labels -o=wide -l"
abbr --add kgstsslowidel "kubectl get statefulset --show-labels -o=wide -l"
abbr --add ksysgstsslowidel "kubectl --namespace=kube-system get statefulset --show-labels -o=wide -l"
abbr --add kgsvcslowidel "kubectl get service --show-labels -o=wide -l"
abbr --add ksysgsvcslowidel "kubectl --namespace=kube-system get service --show-labels -o=wide -l"
abbr --add kgingslowidel "kubectl get ingress --show-labels -o=wide -l"
abbr --add ksysgingslowidel "kubectl --namespace=kube-system get ingress --show-labels -o=wide -l"
abbr --add kgcmslowidel "kubectl get configmap --show-labels -o=wide -l"
abbr --add ksysgcmslowidel "kubectl --namespace=kube-system get configmap --show-labels -o=wide -l"
abbr --add kgsecslowidel "kubectl get secret --show-labels -o=wide -l"
abbr --add ksysgsecslowidel "kubectl --namespace=kube-system get secret --show-labels -o=wide -l"
abbr --add kgnoslowidel "kubectl get nodes --show-labels -o=wide -l"
abbr --add kgnsslowidel "kubectl get namespaces --show-labels -o=wide -l"
abbr --add kgwowidel "kubectl get --watch -o=wide -l"
abbr --add ksysgwowidel "kubectl --namespace=kube-system get --watch -o=wide -l"
abbr --add kgpowowidel "kubectl get pods --watch -o=wide -l"
abbr --add ksysgpowowidel "kubectl --namespace=kube-system get pods --watch -o=wide -l"
abbr --add kgdepwowidel "kubectl get deployment --watch -o=wide -l"
abbr --add ksysgdepwowidel "kubectl --namespace=kube-system get deployment --watch -o=wide -l"
abbr --add kgstswowidel "kubectl get statefulset --watch -o=wide -l"
abbr --add ksysgstswowidel "kubectl --namespace=kube-system get statefulset --watch -o=wide -l"
abbr --add kgsvcwowidel "kubectl get service --watch -o=wide -l"
abbr --add ksysgsvcwowidel "kubectl --namespace=kube-system get service --watch -o=wide -l"
abbr --add kgingwowidel "kubectl get ingress --watch -o=wide -l"
abbr --add ksysgingwowidel "kubectl --namespace=kube-system get ingress --watch -o=wide -l"
abbr --add kgcmwowidel "kubectl get configmap --watch -o=wide -l"
abbr --add ksysgcmwowidel "kubectl --namespace=kube-system get configmap --watch -o=wide -l"
abbr --add kgsecwowidel "kubectl get secret --watch -o=wide -l"
abbr --add ksysgsecwowidel "kubectl --namespace=kube-system get secret --watch -o=wide -l"
abbr --add kgnowowidel "kubectl get nodes --watch -o=wide -l"
abbr --add kgnswowidel "kubectl get namespaces --watch -o=wide -l"
abbr --add kgwojsonl "kubectl get --watch -o=json -l"
abbr --add ksysgwojsonl "kubectl --namespace=kube-system get --watch -o=json -l"
abbr --add kgpowojsonl "kubectl get pods --watch -o=json -l"
abbr --add ksysgpowojsonl "kubectl --namespace=kube-system get pods --watch -o=json -l"
abbr --add kgdepwojsonl "kubectl get deployment --watch -o=json -l"
abbr --add ksysgdepwojsonl "kubectl --namespace=kube-system get deployment --watch -o=json -l"
abbr --add kgstswojsonl "kubectl get statefulset --watch -o=json -l"
abbr --add ksysgstswojsonl "kubectl --namespace=kube-system get statefulset --watch -o=json -l"
abbr --add kgsvcwojsonl "kubectl get service --watch -o=json -l"
abbr --add ksysgsvcwojsonl "kubectl --namespace=kube-system get service --watch -o=json -l"
abbr --add kgingwojsonl "kubectl get ingress --watch -o=json -l"
abbr --add ksysgingwojsonl "kubectl --namespace=kube-system get ingress --watch -o=json -l"
abbr --add kgcmwojsonl "kubectl get configmap --watch -o=json -l"
abbr --add ksysgcmwojsonl "kubectl --namespace=kube-system get configmap --watch -o=json -l"
abbr --add kgsecwojsonl "kubectl get secret --watch -o=json -l"
abbr --add ksysgsecwojsonl "kubectl --namespace=kube-system get secret --watch -o=json -l"
abbr --add kgnowojsonl "kubectl get nodes --watch -o=json -l"
abbr --add kgnswojsonl "kubectl get namespaces --watch -o=json -l"
abbr --add kgslwl "kubectl get --show-labels --watch -l"
abbr --add ksysgslwl "kubectl --namespace=kube-system get --show-labels --watch -l"
abbr --add kgposlwl "kubectl get pods --show-labels --watch -l"
abbr --add ksysgposlwl "kubectl --namespace=kube-system get pods --show-labels --watch -l"
abbr --add kgdepslwl "kubectl get deployment --show-labels --watch -l"
abbr --add ksysgdepslwl "kubectl --namespace=kube-system get deployment --show-labels --watch -l"
abbr --add kgstsslwl "kubectl get statefulset --show-labels --watch -l"
abbr --add ksysgstsslwl "kubectl --namespace=kube-system get statefulset --show-labels --watch -l"
abbr --add kgsvcslwl "kubectl get service --show-labels --watch -l"
abbr --add ksysgsvcslwl "kubectl --namespace=kube-system get service --show-labels --watch -l"
abbr --add kgingslwl "kubectl get ingress --show-labels --watch -l"
abbr --add ksysgingslwl "kubectl --namespace=kube-system get ingress --show-labels --watch -l"
abbr --add kgcmslwl "kubectl get configmap --show-labels --watch -l"
abbr --add ksysgcmslwl "kubectl --namespace=kube-system get configmap --show-labels --watch -l"
abbr --add kgsecslwl "kubectl get secret --show-labels --watch -l"
abbr --add ksysgsecslwl "kubectl --namespace=kube-system get secret --show-labels --watch -l"
abbr --add kgnoslwl "kubectl get nodes --show-labels --watch -l"
abbr --add kgnsslwl "kubectl get namespaces --show-labels --watch -l"
abbr --add kgwsll "kubectl get --watch --show-labels -l"
abbr --add ksysgwsll "kubectl --namespace=kube-system get --watch --show-labels -l"
abbr --add kgpowsll "kubectl get pods --watch --show-labels -l"
abbr --add ksysgpowsll "kubectl --namespace=kube-system get pods --watch --show-labels -l"
abbr --add kgdepwsll "kubectl get deployment --watch --show-labels -l"
abbr --add ksysgdepwsll "kubectl --namespace=kube-system get deployment --watch --show-labels -l"
abbr --add kgstswsll "kubectl get statefulset --watch --show-labels -l"
abbr --add ksysgstswsll "kubectl --namespace=kube-system get statefulset --watch --show-labels -l"
abbr --add kgsvcwsll "kubectl get service --watch --show-labels -l"
abbr --add ksysgsvcwsll "kubectl --namespace=kube-system get service --watch --show-labels -l"
abbr --add kgingwsll "kubectl get ingress --watch --show-labels -l"
abbr --add ksysgingwsll "kubectl --namespace=kube-system get ingress --watch --show-labels -l"
abbr --add kgcmwsll "kubectl get configmap --watch --show-labels -l"
abbr --add ksysgcmwsll "kubectl --namespace=kube-system get configmap --watch --show-labels -l"
abbr --add kgsecwsll "kubectl get secret --watch --show-labels -l"
abbr --add ksysgsecwsll "kubectl --namespace=kube-system get secret --watch --show-labels -l"
abbr --add kgnowsll "kubectl get nodes --watch --show-labels -l"
abbr --add kgnswsll "kubectl get namespaces --watch --show-labels -l"
abbr --add kgslwowidel "kubectl get --show-labels --watch -o=wide -l"
abbr --add ksysgslwowidel "kubectl --namespace=kube-system get --show-labels --watch -o=wide -l"
abbr --add kgposlwowidel "kubectl get pods --show-labels --watch -o=wide -l"
abbr --add ksysgposlwowidel "kubectl --namespace=kube-system get pods --show-labels --watch -o=wide -l"
abbr --add kgdepslwowidel "kubectl get deployment --show-labels --watch -o=wide -l"
abbr --add ksysgdepslwowidel "kubectl --namespace=kube-system get deployment --show-labels --watch -o=wide -l"
abbr --add kgstsslwowidel "kubectl get statefulset --show-labels --watch -o=wide -l"
abbr --add ksysgstsslwowidel "kubectl --namespace=kube-system get statefulset --show-labels --watch -o=wide -l"
abbr --add kgsvcslwowidel "kubectl get service --show-labels --watch -o=wide -l"
abbr --add ksysgsvcslwowidel "kubectl --namespace=kube-system get service --show-labels --watch -o=wide -l"
abbr --add kgingslwowidel "kubectl get ingress --show-labels --watch -o=wide -l"
abbr --add ksysgingslwowidel "kubectl --namespace=kube-system get ingress --show-labels --watch -o=wide -l"
abbr --add kgcmslwowidel "kubectl get configmap --show-labels --watch -o=wide -l"
abbr --add ksysgcmslwowidel "kubectl --namespace=kube-system get configmap --show-labels --watch -o=wide -l"
abbr --add kgsecslwowidel "kubectl get secret --show-labels --watch -o=wide -l"
abbr --add ksysgsecslwowidel "kubectl --namespace=kube-system get secret --show-labels --watch -o=wide -l"
abbr --add kgnoslwowidel "kubectl get nodes --show-labels --watch -o=wide -l"
abbr --add kgnsslwowidel "kubectl get namespaces --show-labels --watch -o=wide -l"
abbr --add kgwowidesll "kubectl get --watch -o=wide --show-labels -l"
abbr --add ksysgwowidesll "kubectl --namespace=kube-system get --watch -o=wide --show-labels -l"
abbr --add kgpowowidesll "kubectl get pods --watch -o=wide --show-labels -l"
abbr --add ksysgpowowidesll "kubectl --namespace=kube-system get pods --watch -o=wide --show-labels -l"
abbr --add kgdepwowidesll "kubectl get deployment --watch -o=wide --show-labels -l"
abbr --add ksysgdepwowidesll "kubectl --namespace=kube-system get deployment --watch -o=wide --show-labels -l"
abbr --add kgstswowidesll "kubectl get statefulset --watch -o=wide --show-labels -l"
abbr --add ksysgstswowidesll "kubectl --namespace=kube-system get statefulset --watch -o=wide --show-labels -l"
abbr --add kgsvcwowidesll "kubectl get service --watch -o=wide --show-labels -l"
abbr --add ksysgsvcwowidesll "kubectl --namespace=kube-system get service --watch -o=wide --show-labels -l"
abbr --add kgingwowidesll "kubectl get ingress --watch -o=wide --show-labels -l"
abbr --add ksysgingwowidesll "kubectl --namespace=kube-system get ingress --watch -o=wide --show-labels -l"
abbr --add kgcmwowidesll "kubectl get configmap --watch -o=wide --show-labels -l"
abbr --add ksysgcmwowidesll "kubectl --namespace=kube-system get configmap --watch -o=wide --show-labels -l"
abbr --add kgsecwowidesll "kubectl get secret --watch -o=wide --show-labels -l"
abbr --add ksysgsecwowidesll "kubectl --namespace=kube-system get secret --watch -o=wide --show-labels -l"
abbr --add kgnowowidesll "kubectl get nodes --watch -o=wide --show-labels -l"
abbr --add kgnswowidesll "kubectl get namespaces --watch -o=wide --show-labels -l"
abbr --add kgwslowidel "kubectl get --watch --show-labels -o=wide -l"
abbr --add ksysgwslowidel "kubectl --namespace=kube-system get --watch --show-labels -o=wide -l"
abbr --add kgpowslowidel "kubectl get pods --watch --show-labels -o=wide -l"
abbr --add ksysgpowslowidel "kubectl --namespace=kube-system get pods --watch --show-labels -o=wide -l"
abbr --add kgdepwslowidel "kubectl get deployment --watch --show-labels -o=wide -l"
abbr --add ksysgdepwslowidel "kubectl --namespace=kube-system get deployment --watch --show-labels -o=wide -l"
abbr --add kgstswslowidel "kubectl get statefulset --watch --show-labels -o=wide -l"
abbr --add ksysgstswslowidel "kubectl --namespace=kube-system get statefulset --watch --show-labels -o=wide -l"
abbr --add kgsvcwslowidel "kubectl get service --watch --show-labels -o=wide -l"
abbr --add ksysgsvcwslowidel "kubectl --namespace=kube-system get service --watch --show-labels -o=wide -l"
abbr --add kgingwslowidel "kubectl get ingress --watch --show-labels -o=wide -l"
abbr --add ksysgingwslowidel "kubectl --namespace=kube-system get ingress --watch --show-labels -o=wide -l"
abbr --add kgcmwslowidel "kubectl get configmap --watch --show-labels -o=wide -l"
abbr --add ksysgcmwslowidel "kubectl --namespace=kube-system get configmap --watch --show-labels -o=wide -l"
abbr --add kgsecwslowidel "kubectl get secret --watch --show-labels -o=wide -l"
abbr --add ksysgsecwslowidel "kubectl --namespace=kube-system get secret --watch --show-labels -o=wide -l"
abbr --add kgnowslowidel "kubectl get nodes --watch --show-labels -o=wide -l"
abbr --add kgnswslowidel "kubectl get namespaces --watch --show-labels -o=wide -l"
abbr --add kexn "kubectl exec -i -t --namespace"
abbr --add klon "kubectl logs -f --namespace"
abbr --add kpfn "kubectl port-forward --namespace"
abbr --add kgn "kubectl get --namespace"
abbr --add kdn "kubectl describe --namespace"
abbr --add krmn "kubectl delete --namespace"
abbr --add kgpon "kubectl get pods --namespace"
abbr --add kdpon "kubectl describe pods --namespace"
abbr --add krmpon "kubectl delete pods --namespace"
abbr --add kgdepn "kubectl get deployment --namespace"
abbr --add kddepn "kubectl describe deployment --namespace"
abbr --add krmdepn "kubectl delete deployment --namespace"
abbr --add kgstsn "kubectl get statefulset --namespace"
abbr --add kdstsn "kubectl describe statefulset --namespace"
abbr --add krmstsn "kubectl delete statefulset --namespace"
abbr --add kgsvcn "kubectl get service --namespace"
abbr --add kdsvcn "kubectl describe service --namespace"
abbr --add krmsvcn "kubectl delete service --namespace"
abbr --add kgingn "kubectl get ingress --namespace"
abbr --add kdingn "kubectl describe ingress --namespace"
abbr --add krmingn "kubectl delete ingress --namespace"
abbr --add kgcmn "kubectl get configmap --namespace"
abbr --add kdcmn "kubectl describe configmap --namespace"
abbr --add krmcmn "kubectl delete configmap --namespace"
abbr --add kgsecn "kubectl get secret --namespace"
abbr --add kdsecn "kubectl describe secret --namespace"
abbr --add krmsecn "kubectl delete secret --namespace"
abbr --add kgoyamln "kubectl get -o=yaml --namespace"
abbr --add kgpooyamln "kubectl get pods -o=yaml --namespace"
abbr --add kgdepoyamln "kubectl get deployment -o=yaml --namespace"
abbr --add kgstsoyamln "kubectl get statefulset -o=yaml --namespace"
abbr --add kgsvcoyamln "kubectl get service -o=yaml --namespace"
abbr --add kgingoyamln "kubectl get ingress -o=yaml --namespace"
abbr --add kgcmoyamln "kubectl get configmap -o=yaml --namespace"
abbr --add kgsecoyamln "kubectl get secret -o=yaml --namespace"
abbr --add kgowiden "kubectl get -o=wide --namespace"
abbr --add kgpoowiden "kubectl get pods -o=wide --namespace"
abbr --add kgdepowiden "kubectl get deployment -o=wide --namespace"
abbr --add kgstsowiden "kubectl get statefulset -o=wide --namespace"
abbr --add kgsvcowiden "kubectl get service -o=wide --namespace"
abbr --add kgingowiden "kubectl get ingress -o=wide --namespace"
abbr --add kgcmowiden "kubectl get configmap -o=wide --namespace"
abbr --add kgsecowiden "kubectl get secret -o=wide --namespace"
abbr --add kgojsonn "kubectl get -o=json --namespace"
abbr --add kgpoojsonn "kubectl get pods -o=json --namespace"
abbr --add kgdepojsonn "kubectl get deployment -o=json --namespace"
abbr --add kgstsojsonn "kubectl get statefulset -o=json --namespace"
abbr --add kgsvcojsonn "kubectl get service -o=json --namespace"
abbr --add kgingojsonn "kubectl get ingress -o=json --namespace"
abbr --add kgcmojsonn "kubectl get configmap -o=json --namespace"
abbr --add kgsecojsonn "kubectl get secret -o=json --namespace"
abbr --add kgsln "kubectl get --show-labels --namespace"
abbr --add kgposln "kubectl get pods --show-labels --namespace"
abbr --add kgdepsln "kubectl get deployment --show-labels --namespace"
abbr --add kgstssln "kubectl get statefulset --show-labels --namespace"
abbr --add kgsvcsln "kubectl get service --show-labels --namespace"
abbr --add kgingsln "kubectl get ingress --show-labels --namespace"
abbr --add kgcmsln "kubectl get configmap --show-labels --namespace"
abbr --add kgsecsln "kubectl get secret --show-labels --namespace"
abbr --add kgwn "kubectl get --watch --namespace"
abbr --add kgpown "kubectl get pods --watch --namespace"
abbr --add kgdepwn "kubectl get deployment --watch --namespace"
abbr --add kgstswn "kubectl get statefulset --watch --namespace"
abbr --add kgsvcwn "kubectl get service --watch --namespace"
abbr --add kgingwn "kubectl get ingress --watch --namespace"
abbr --add kgcmwn "kubectl get configmap --watch --namespace"
abbr --add kgsecwn "kubectl get secret --watch --namespace"
abbr --add kgwoyamln "kubectl get --watch -o=yaml --namespace"
abbr --add kgpowoyamln "kubectl get pods --watch -o=yaml --namespace"
abbr --add kgdepwoyamln "kubectl get deployment --watch -o=yaml --namespace"
abbr --add kgstswoyamln "kubectl get statefulset --watch -o=yaml --namespace"
abbr --add kgsvcwoyamln "kubectl get service --watch -o=yaml --namespace"
abbr --add kgingwoyamln "kubectl get ingress --watch -o=yaml --namespace"
abbr --add kgcmwoyamln "kubectl get configmap --watch -o=yaml --namespace"
abbr --add kgsecwoyamln "kubectl get secret --watch -o=yaml --namespace"
abbr --add kgowidesln "kubectl get -o=wide --show-labels --namespace"
abbr --add kgpoowidesln "kubectl get pods -o=wide --show-labels --namespace"
abbr --add kgdepowidesln "kubectl get deployment -o=wide --show-labels --namespace"
abbr --add kgstsowidesln "kubectl get statefulset -o=wide --show-labels --namespace"
abbr --add kgsvcowidesln "kubectl get service -o=wide --show-labels --namespace"
abbr --add kgingowidesln "kubectl get ingress -o=wide --show-labels --namespace"
abbr --add kgcmowidesln "kubectl get configmap -o=wide --show-labels --namespace"
abbr --add kgsecowidesln "kubectl get secret -o=wide --show-labels --namespace"
abbr --add kgslowiden "kubectl get --show-labels -o=wide --namespace"
abbr --add kgposlowiden "kubectl get pods --show-labels -o=wide --namespace"
abbr --add kgdepslowiden "kubectl get deployment --show-labels -o=wide --namespace"
abbr --add kgstsslowiden "kubectl get statefulset --show-labels -o=wide --namespace"
abbr --add kgsvcslowiden "kubectl get service --show-labels -o=wide --namespace"
abbr --add kgingslowiden "kubectl get ingress --show-labels -o=wide --namespace"
abbr --add kgcmslowiden "kubectl get configmap --show-labels -o=wide --namespace"
abbr --add kgsecslowiden "kubectl get secret --show-labels -o=wide --namespace"
abbr --add kgwowiden "kubectl get --watch -o=wide --namespace"
abbr --add kgpowowiden "kubectl get pods --watch -o=wide --namespace"
abbr --add kgdepwowiden "kubectl get deployment --watch -o=wide --namespace"
abbr --add kgstswowiden "kubectl get statefulset --watch -o=wide --namespace"
abbr --add kgsvcwowiden "kubectl get service --watch -o=wide --namespace"
abbr --add kgingwowiden "kubectl get ingress --watch -o=wide --namespace"
abbr --add kgcmwowiden "kubectl get configmap --watch -o=wide --namespace"
abbr --add kgsecwowiden "kubectl get secret --watch -o=wide --namespace"
abbr --add kgwojsonn "kubectl get --watch -o=json --namespace"
abbr --add kgpowojsonn "kubectl get pods --watch -o=json --namespace"
abbr --add kgdepwojsonn "kubectl get deployment --watch -o=json --namespace"
abbr --add kgstswojsonn "kubectl get statefulset --watch -o=json --namespace"
abbr --add kgsvcwojsonn "kubectl get service --watch -o=json --namespace"
abbr --add kgingwojsonn "kubectl get ingress --watch -o=json --namespace"
abbr --add kgcmwojsonn "kubectl get configmap --watch -o=json --namespace"
abbr --add kgsecwojsonn "kubectl get secret --watch -o=json --namespace"
abbr --add kgslwn "kubectl get --show-labels --watch --namespace"
abbr --add kgposlwn "kubectl get pods --show-labels --watch --namespace"
abbr --add kgdepslwn "kubectl get deployment --show-labels --watch --namespace"
abbr --add kgstsslwn "kubectl get statefulset --show-labels --watch --namespace"
abbr --add kgsvcslwn "kubectl get service --show-labels --watch --namespace"
abbr --add kgingslwn "kubectl get ingress --show-labels --watch --namespace"
abbr --add kgcmslwn "kubectl get configmap --show-labels --watch --namespace"
abbr --add kgsecslwn "kubectl get secret --show-labels --watch --namespace"
abbr --add kgwsln "kubectl get --watch --show-labels --namespace"
abbr --add kgpowsln "kubectl get pods --watch --show-labels --namespace"
abbr --add kgdepwsln "kubectl get deployment --watch --show-labels --namespace"
abbr --add kgstswsln "kubectl get statefulset --watch --show-labels --namespace"
abbr --add kgsvcwsln "kubectl get service --watch --show-labels --namespace"
abbr --add kgingwsln "kubectl get ingress --watch --show-labels --namespace"
abbr --add kgcmwsln "kubectl get configmap --watch --show-labels --namespace"
abbr --add kgsecwsln "kubectl get secret --watch --show-labels --namespace"
abbr --add kgslwowiden "kubectl get --show-labels --watch -o=wide --namespace"
abbr --add kgposlwowiden "kubectl get pods --show-labels --watch -o=wide --namespace"
abbr --add kgdepslwowiden "kubectl get deployment --show-labels --watch -o=wide --namespace"
abbr --add kgstsslwowiden "kubectl get statefulset --show-labels --watch -o=wide --namespace"
abbr --add kgsvcslwowiden "kubectl get service --show-labels --watch -o=wide --namespace"
abbr --add kgingslwowiden "kubectl get ingress --show-labels --watch -o=wide --namespace"
abbr --add kgcmslwowiden "kubectl get configmap --show-labels --watch -o=wide --namespace"
abbr --add kgsecslwowiden "kubectl get secret --show-labels --watch -o=wide --namespace"
abbr --add kgwowidesln "kubectl get --watch -o=wide --show-labels --namespace"
abbr --add kgpowowidesln "kubectl get pods --watch -o=wide --show-labels --namespace"
abbr --add kgdepwowidesln "kubectl get deployment --watch -o=wide --show-labels --namespace"
abbr --add kgstswowidesln "kubectl get statefulset --watch -o=wide --show-labels --namespace"
abbr --add kgsvcwowidesln "kubectl get service --watch -o=wide --show-labels --namespace"
abbr --add kgingwowidesln "kubectl get ingress --watch -o=wide --show-labels --namespace"
abbr --add kgcmwowidesln "kubectl get configmap --watch -o=wide --show-labels --namespace"
abbr --add kgsecwowidesln "kubectl get secret --watch -o=wide --show-labels --namespace"
abbr --add kgwslowiden "kubectl get --watch --show-labels -o=wide --namespace"
abbr --add kgpowslowiden "kubectl get pods --watch --show-labels -o=wide --namespace"
abbr --add kgdepwslowiden "kubectl get deployment --watch --show-labels -o=wide --namespace"
abbr --add kgstswslowiden "kubectl get statefulset --watch --show-labels -o=wide --namespace"
abbr --add kgsvcwslowiden "kubectl get service --watch --show-labels -o=wide --namespace"
abbr --add kgingwslowiden "kubectl get ingress --watch --show-labels -o=wide --namespace"
abbr --add kgcmwslowiden "kubectl get configmap --watch --show-labels -o=wide --namespace"
abbr --add kgsecwslowiden "kubectl get secret --watch --show-labels -o=wide --namespace"
